### ISSUE TITLE
Accessing parent data context

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#1]
What would be good API for accessing parent data context? Blaze's access by fixed number of levels is really fragile to cod refactoring.

Do we even need it? In the past, in most cases when I needed parent data context was to access what we now have a as a top-level component data context.

And maybe we just have to support accessing parent components, and then use `.data()` on them to access the data context there?

So, what are use cases?

**Comment by kostko** [comment]
Doesn't such direct access to the parent context introduce tight coupling to the place where the component is included and perhaps even the internals of the parent component? Shouldn't components be (mostly) independent and most state passed via arguments to components?

I agree that there should still be a way to get the parent component instance (one level) and access things via its public methods/attributes, but some things in the parent data context may be internal and should not all just be exposed?

**Comment by mitar** [comment]
With 25f4545ef342d5cb84f66dde8caedbf12346570b we have an option to navigate between parent and children components and I think this is good enough for now. Let's see if we need more options for data context navigation later on. So you can access parent component data context now with `componentParent().data()`.
