### ISSUE TITLE
Change getMixinWith and callMixinWith

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-blaze-components#10]
`getMixinWith` allows to not specify `afterMixin`, but expects it as the first property. If we change the signature to:

```
getMixinWith: (propertyName, afterMixin) ->
```

we can have cleaner calls `getMixinWith 'value'` instead of `getMixinWith null, 'value'`

Same applies to `callMixinWith`.

I also propose to change `callMixinWith` to something else. `callMixinWith` to me doesn't sound great, because it sounds ambiguous to what is being called (are you calling a mixin? how do you call a mixin?). It works really well for `getMixinWith` as in `getMixinWith 'value'`, but in the call case I hope we can find something better, ideally more aligned to `super`. This should go hand in hand with `callMixins` that returns the array of results.

Possible ideas:
- `callMixin 'value'` and `callMixins 'value'`
  
  This implies that we want `value` that comes from a mixin. You don't care which mixin, just that it comes from a mixin, which is exactly what this method does. 
- `callMixins 'value'` and `callAllMixins 'value'`
  
  Because the call does in fact go over all the mixins, this naming preserves more of how the thing is implemented. So you call mixins to find `value`. And if you want all the results (in an array) you are specific to call all mixins.
- `fromMixin 'value'` and `fromMixins 'value'` or
  `fromMixins 'value'` and `fromAllMixins 'value'`
  
  Alternative naming that more explicitly expresses that we want `value` that comes from a mixin. But it loses the maybe important notion that a function call is executed.

**Comment by mitar** [comment]
See #3 for a bit of background on the current API.

**Comment by MatejJan** [comment]
(I forgot to confirm the comment before, so I'm a bit late with this. :))

Hm, now that I think about it from another perspective, the last two bullet points are not good.

Let's say the function we need to call is `draw`.

In the second bullet point `callMixins 'draw'` incorrectly implies that draw will be called on more of them, which is not true. Sure, there is the `callAllMixins` that implies that first one probably doesn't call all, but that is not good enough. Also my original statement from that bullet point ("the call does in fact go over all the mixins") is simply not true. We go over the mixins, but the call is only executed on the first one.

The `from` naming is simply bad when you think about functions as functions (that might not even return a value) and not properties.

But `callMixin` is still good I think, because it has singular `mixin` in the name and goes nicely with `callMixins` (the same, but just operates on one mixin).

Also, so that in the args case we don't have to call the ugly `callMixin 'draw', null, dt`, we could have the version with `afterMixin` separately, named something like `callMixinAfter` or `callNearestMixin`.

And if we really want to be specific, instead of `callMixin` we would have `callFirstMixin`. So then we have `callFirstMixin`, `callMixinAfter` and `callAllMixins`, but I prefer just `callMixin`.

**Comment by mitar** [comment]
I agree that position of `afterMixin` argument is not the best, but it was done so that it matches the one of `callMixinWith`, so that it is easy to pass additional arguments.

I agree that it is cumbersome to pass initial arguments, but maybe I am too used to Python, where you pass `self` in call to `super`, so for me is a bit more natural. :-) This is also why you can simply pass `@` always as a first argument in a component as well. So that it works similarly to Python, where you pass what your instance is and the system figures out who to call next.

**Comment by MatejJan** [comment]
> See #3 for a bit of background on the current API.

Yeah, sorry for not giving you feedback back then already. I'm just getting back to this now.

**Comment by mitar** [comment]
> But callMixin is still good I think, because it has singular mixin in the name and goes nicely with callMixins (the same, but just operates on one mixin).

My issue here is that it is only one letter difference which can open an easy path to bugs.

> Also, so that in the args case we don't have to call the ugly callMixin 'draw', null, dt, we could have the version with afterMixin separately, named something like callMixinAfter or callNearestMixin.

We had that before (see #3), I tried to simplify. :-) Not saying that we cannot go back, but I was thinking that I more like the Python `super` approach where you just call it and it figures out where to go next which is often exactly what you want.

**Comment by mitar** [comment]
Renamed to `getFirstWith` and `callFirstWith`. Main change is that it can return/call the component itself as well.

I am also removing `callMixins`. Its semantics are hard to generalize. People can implement that themselves.
