### ISSUE TITLE
this.parentComponent() and this.childComponents() are not working

### ISSUE THREAD

**Issue by kokjinsam** [peerlibrary/meteor-blaze-components#102]
I'm not sure I'm doing something wrong but here's my use case:

Let's say I have two components namely componentA and componentB:

```
componentA = BlazeComponent.extendComponent({
    onRendered: function() {
      console.log(this.componentName()+' child component is '+this.childComponents());
});
```

and

```
componentB = BlazeComponent.extendComponent({
    onRendered: function() {
      console.log(this.componentName()+' parent component is '+this.parentComponent());
});
```

In a HTML file, I have something like this:

```
<body>
{{#componentA}}
    {{>componentB}}
    {{>componentB}}
{{/componentA}}
</body>
```

Both this.parentComponent() and this.childComponents() return null. In this case, am I doing something wrong?

**Comment by mitar** [comment]
I think this is duplicate of #50. The current design is that block components are not in a component tree, but siblings. Use `dumpAllComponents` to see the component tree to better understand what is happening.

I agree this is unexpected behavior and should probably be fixed.

**Comment by kokjinsam** [comment]
Ahh. Thanks for clearing it up!
