### ISSUE TITLE
Problems with Namespace

### ISSUE THREAD

**Issue by thebarty** [peerlibrary/meteor-blaze-components#103]
Hi guys,

I ran into a problem using this with in an all-in-packages structure and a global namespace.

How do I attach a Blaze-Component to a global namespace from within an package?

This example right here destroys my namespace and DOES NOT work - it destroys the namespace within other packages:

```
// assume that we have a global namespace ``Su`` available
//  and we want to attach a component to it
Su.UseCase = {};  // namespace for  use-case
Su.UseCase.ListComponent = class ListComponent extends BlazeComponent {
  // this destroys the namespace in other packages
}
```

Any ideas?

By the way: I also posted this in meteor forum https://forums.meteor.com/t/es6-how-to-attach-blaze-component-to-global-namespace-within-package/12753/1

**Comment by mitar** [comment]
Maybe:

```
Su.UseCase = Su.UseCase || {};  // namespace for  use-case
Su.UseCase.ListComponent = class ListComponent extends BlazeComponent {
  // this destroys the namespace in other packages
}
```

**Comment by thebarty** [comment]
@mitar: thanks for the response!!

I found out that it was the register function that gave me problems.

So this is the code that works:

```
Su.UseCase = Su.UseCase || {};  // namespace for  use-case
Su.UseCase.ListComponent = class ListComponent extends BlazeComponent {
  ...
}
Su.UseCase.ListComponent.register('SuUseCaseListComponent', UseCase.ListComponent);
``
```
