### ISSUE TITLE
Could I use "AutoForm.hook()" in the Blaze Component?

### ISSUE THREAD

**Issue by thearabbit** [peerlibrary/meteor-blaze-components#104]
Could I use "AutoForm.hook()" in the Blaze Component?

``` js
class ExampleComponent extends BlazeComponent {
  // Life-cycle hook to initialize component's state.
  onCreated() {
    // It is a good practice to always call super.
    super.onCreated();
    this.counter = new ReactiveField(0);
  }
  autoformHook:{.............}
```

**Comment by mitar** [comment]
I don't know what that does.

**Comment by thearabbit** [comment]
I would like to use `state` in this template with `AutoForm.hooks({........})`.
Before I declare the global `reactiveVar`.

**Comment by mitar** [comment]
Interesting idea. I have not tried that. But I guess you could do something like:

``` javascript
AutoForm.addHooks(ExampleComponent.componentName(), ExampleComponent.prototype)
```

After the declaration of your component. And then component methods matching the name of class would be called for you. I am just not sure if `this` will be the component or something else.

Maybe @aldeed can help here more.
