### ISSUE TITLE
Rendered content selector scope?

### ISSUE THREAD

**Issue by JesperWe** [peerlibrary/meteor-blaze-components#106]
The documentation section on **Access to Rendered Content** says:

> The component serves as the document root for the selector. Only elements inside the component and its sub-components can match parts of the selector.

I am having trouble with this when I have two copies of a component instantiated on the same page. A `$("#foo")` selector in an event handler in the second instance gives me the element from the first. Have I not understood this correctly?

**Comment by JesperWe** [comment]
OK, now I have understood :-)  
I have realized all the documented stuff is relative to `this`, so need `this.$()`, not `$()`

**Comment by mitar** [comment]
Yes. And also have in mind that IDs have to be unique on the page. So `#foo` should always match only one element anyway.
