### ISSUE TITLE
Getting errors after upgrading into 0.16

### ISSUE THREAD

**Issue by chompomonim** [peerlibrary/meteor-blaze-components#111]
```
conflict: two packages included in the app (templating and peerlibrary:blaze-components) are both trying to handle *.html
```

**Comment by mitar** [comment]
Please read the [installation section](https://github.com/peerlibrary/meteor-blaze-components#installation).

**Comment by chompomonim** [comment]
```
$ meteor remove blaze-html-templates
meteor remove templating
blaze-html-templates: removed dependency

$ meteor remove templating
templating is not in this project.

$ meteor add peerlibrary:blaze-components

Changes to your projects package version selections:

peerlibrary:assert            added, version 0.2.5
peerlibrary:base-component    added, version 0.14.0
peerlibrary:blaze-components  added, version 0.16.0
peerlibrary:computed-field    added, version 0.3.1
peerlibrary:data-lookup       added, version 0.1.0
peerlibrary:reactive-field    added, version 0.1.0


peerlibrary:blaze-components: Reusable components for Blaze

$ meteor
[[[[[ ~/Dev/Meteor/demo ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While determining active plugins:
   error: conflict: two packages included in the app (templating and peerlibrary:blaze-components) are both trying to handle *.html

   While determining active plugins:
   error: conflict: two packages included in the app (templating and peerlibrary:blaze-components) are both trying to handle *.html

=> Your application has errors. Waiting for file change.
```

**Comment by mitar** [comment]
Can you share the code? Or at least your `.meteor/packages`? Do you use any packages, which depend both on `templating` and Blaze Components?

**Comment by chompomonim** [comment]
My `.meteor/packages`:

```
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

standard-minifiers
meteor-base
mobile-experience
mongo
session
jquery
tracker
logging
reload
random
ejson
spacebars
check

coffeescript
mquandalle:jade

aldeed:simple-schema
aldeed:autoform
fabienb4:autoform-semantic-ui

accounts-ui
accounts-password
useraccounts:flow-routing
useraccounts:semantic-ui

stolinski:stylus-multi
semantic:ui-css

kadira:flow-router
arillo:flow-router-helpers
kadira:blaze-layout
reactive-var
nous:utils-and-helpers
meteorflux:reactive-state
momentjs:moment
matb33:collection-hooks
dburles:collection-helpers

orionjs:core
dvz:orion-semantic-ui
orionjs:relationships
orionjs:froala
orionjs:filesystem
vsivsi:orion-file-collection
orionjs:image-attribute

meteorhacks:kadira
msavin:mongol
msavin:jetsetter

peerlibrary:blaze-components
```

**Comment by mitar** [comment]
Hm, this is really a bad error message. It seems one of your packages `imply` `templating` and this is why you are getting this error. Good luck figuring out which one. I opened https://github.com/meteor/meteor/issues/5911.

**Comment by mitar** [comment]
The following two packages are conflicting:
- `orionjs:core`: because of [this line](https://github.com/orionjs/orion/blob/master/packages/base/package.js#L37)
- `dvz:orion-semantic-ui`: because of [this line](https://github.com/amazingBastard/orion-semantic-ui/blob/master/package.js#L22)

**Comment by mitar** [comment]
I opened https://github.com/orionjs/orion/pull/381.

**Comment by mitar** [comment]
And https://github.com/amazingBastard/orion-semantic-ui/pull/5.

**Comment by mitar** [comment]
Anyway, a better approach than having all package dependencies on the project level, is to use packages to structure your app. Then your packages can depend on different other packages which can both process HTML files.

**Comment by chompomonim** [comment]
@mitar big thanks for taking time for this and for your advice.

**Comment by gbisheimer** [comment]
The same happened to me when trying to use codefights:blaze-material-ui because of [this line](https://github.com/Code-Fights/blaze-material-ui/blob/master/package.js#L24).

Don't know yet if templating is needed or not for blaze-material-ui to work, but will open an issue for this.

**Comment by mitar** [comment]
Thanks for reporting. It is not needed anymore (and in fact it conflicts) because templating is provided through Blaze Components.

**Comment by marcscherer** [comment]
I still got this error message when I try to use 0.16.x. How can I find out which package depends on templating and causes the error?

**Comment by mitar** [comment]
You have to manually go through it. See https://github.com/meteor/meteor/issues/5911

**Comment by mitar** [comment]
But please post what you find here, because it might help others address the issue quicker.

**Comment by marcscherer** [comment]
I found out that gwendall:simple-schema-i18n implies templating. For now I removed the package.

**Comment by mitar** [comment]
Could you report this there?

**Comment by hexsprite** [comment]
I'm having a hard time upgrading to a newer version of blaze-components due to this issue.

I looked through all the dependencies in my app and couldn't see that they implied `templating`. Perhaps I don't understand it well enough.

Here's my `packages` file

```
###
# Meteor standard packages
###
peerlibrary:blaze-components

accounts-base
accounts-google
accounts-ui-unstyled
coffeescript
ecmascript
email
fastclick
standard-app-packages
markdown
promise
reactive-var
reactive-dict
random
service-configuration
standard-minifier-css
standard-minifier-js

###
# Packages requiring specific order
###

###
# Packages (3rd Party)
###
aldeed:autoform
copleykj:jquery-autosize
dsyko:hopscotch
infinitedg:winston
infinitedg:winston-loggly
iron:layout
iron:router
jag:pince
juliancwirko:s-alert
juliancwirko:s-grid
konecty:multiple-instances-status
konecty:user-presence
linto:jquery-ui
mrgalaxy:stripe
natestrauser:animate-css
natestrauser:font-awesome
peerlibrary:assert
peerlibrary:computed-field
peerlibrary:reactive-field
percolate:google-api@=1.0.0
percolate:migrations
percolatestudio:segment.io@1.2.2_1
percolatestudio:synced-cron
utilities:avatar
vsivsi:job-collection
wylio:winston-papertrail
zimme:active-route
lookback:tooltips

###
# Deployment tools
###
meteorhacks:kadira
kadira:debug
meteorhacks:kadira-profiler


###
# Testing Tools
###
google-fake
velocityjs:velocityjs

###
# Local packages
###
hilios:jquery.countdown

###
# Newly added packages, to be sorted
###
alanning:roles
gwendall:impersonate
peerlibrary:server-autorun
peerlibrary:reactive-publish
fongandrew:find-and-modify
chriswessels:hammer
dburles:collection-helpers
dispatch:mocha-browser
meteorhacks:ssr
dispatch:mocha-phantomjs
dispatch:mocha
```

**Comment by mitar** [comment]
The best Meteor architecture is to put all code into local packages instead of having top-level code and top-level packages. In that case you can even use multiple packages in parallel, who handle HTML files.

When you have everything inside top-level packages it really becomes a problem because of possible conflicts between packages like this one.

The issue is that implying can be recursive. Maybe some dependency of a package you are using is doing implying.

The easiest way to detect is to remove few packages and try and see if it is still conflicting and do bisection until you find a package which is problematic.
