### ISSUE TITLE
Possibility to use same template for different components

### ISSUE THREAD

**Issue by chompomonim** [peerlibrary/meteor-blaze-components#114]
I'd like to have:

``` CoffeeScript
class Page extends BlazeComponent
  @register 'pageTemplate'

  page: ->
    Pages.findOne FlowRouter.getParam("_id")

class AnyPage extends Page
  page: ->
    Pages.findOne()
```

``` jade
template(name="pageTemplate")
   h1= page.title
   .content= page.content
```

And in some other template I'd like to do:

``` jade
template(name="dashboard")
  div.current-page
    +Page

  div.any-page
    +AnyPage
```

In React such stuff is totally possible. As far as I understand in blaze-components I should register some additional template.

``` jade
template(name="AnyPage")
  +pageTemplate page=page
```

``` coffeescript
AnyPage.register 'AnyPage'
```

**Comment by mitar** [comment]
No, you can use the same template for different components. The default template name is equal to the component name. But you can override this by returning a different name/template from `template` method. [See here](https://github.com/peerlibrary/meteor-blaze-components#dom-content).

You probably want something like:

``` coffee
class Page extends BlazeComponent
  @register 'Page'

  template: ->
    'pageTemplate'

  page: ->
    Pages.findOne FlowRouter.getParam("_id")

class AnyPage extends Page
  @register 'AnyPage'

  page: ->
    Pages.findOne()
```

**Comment by chompomonim** [comment]
Cool. Thanks.
