### ISSUE TITLE
Support with Meteor 1.3?

### ISSUE THREAD

**Issue by thearabbit** [peerlibrary/meteor-blaze-components#119]
Support with Meteor 1.3?

**Comment by mitar** [comment]
What about it?

**Comment by thearabbit** [comment]
Thanks for your reply, Now I would like to use this package on `Meteor 1.3`.
Suppot?

**Comment by mitar** [comment]
Have you tried to use it? Does it not work?

**Comment by thearabbit** [comment]
I will try.

**Comment by mitar** [comment]
In the future, first try and open tickets only if you see that something does not work. It is not polite to spend time of volunteers without you trying yourself.
