### ISSUE TITLE
[Question] How work nested component? 

### ISSUE THREAD

**Issue by emehmet** [peerlibrary/meteor-blaze-components#122]
Hi, There is ListedWork component this is my root component. And there is a wList() function in this component. And WorkList component is child component of ListedWork. I use this code for list.

`<template name="ListedWork ">
{{#each wList}} {{>workRow}} {{/each}}
</template>
`

```
class WorkRow extends BlazeComponent {

  onCreated(){
    console.log("sdasdsa");
  }

  template() {
    return "workRow";
  }
}

WorkRow.register("WorkRow");
```

```
<template name="workRow">
Work Row test
</template>
```

While functions work in ListedWork, I can't reach functions in WorkRow.  Acting like WorkRow does not.

**Comment by mitar** [comment]
Why you closed the ticket? If you found a solution, please write it down for others.

**Comment by emehmet** [comment]
I'm sorry. I was careless that day i had written lowcase of first character in Template. for example:

{{>workRow}} it should be so {{>WorkRow}}

I couldn't delete so i closed.
