### ISSUE TITLE
Meteor 1.3 update, might give some issues

### ISSUE THREAD

**Issue by bensmeets** [peerlibrary/meteor-blaze-components#127]
Haven't researched yet, but in case it helps. After doing an update to meteor 1.3 and trying to run, I get this error.

```
While determining active plugins:
error: conflict: two packages included in the app (templating and
peerlibrary:blaze-components) are both trying to handle *.html
```

**Comment by mitar** [comment]
This should not have anything with Meteor update. See [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components#installation) installation instructions. In short, just remove `templating` package.

**Comment by bensmeets** [comment]
Cool. Then a heads up for future readers that in my case, the 1.3 update seemed to have re-added that templating package again (I've been using BC a long time, error came after the update)

**Comment by mitar** [comment]
Interesting. Thanks for reporting. Not sure why this would happen.
