### ISSUE TITLE
Is there a way to call autorun() within a function?

### ISSUE THREAD

**Issue by thebarty** [peerlibrary/meteor-blaze-components#128]
Hi guys,

I have a use case where I want to initialize a specific autorun after Meteor.user() is available on the client - which might be AFTER `onCreated()` or `onRendered()`. 

Is there a way to call component-based `autorun()` within a standard(helper) function? Right now I am getting `Exception in defer callback: Error: Can't call View#autorun from a Tracker Computation; try calling it from the created or rendered callback`.

If no: What disadvantages do I get from using `Tracker.autorun`?

Thanks for your help
Barty

**Comment by mitar** [comment]
You should not do anything with side-effects inside helper functions. This is bad practice.

Why don't you simply use `autorun` inside `onCreated` and wait for `Meteor.user()` to become available?

So something like:

``` javascript
onCreated() {
  this.autorun(() => {
    if (!Meteor.userId()) return;

    // the rest
  });
}
```

**Comment by thebarty** [comment]
Hi Mitar, thanks for the lightning speed reply. :+1: 

Well, I have multiple useCases that need this logic and I have written a Mixin to keep it DRY. The Mixin basically waits for the User (it does a bit more) and then calls a hook via `self.mixinParent().callFirstWith(null, 'hookUserIsReady')`. This hook I then simply want to implement in the ParentComponent. Would you consider this bad practise?

**Comment by mitar** [comment]
I think this is good. Just start waiting on `onCreated`. What you should not be doing is having side effects in template helpers. But if methods are not used as a template helper, then it is completely OK to call them. This is how you make code reusable. This is completely OK.

**Comment by mitar** [comment]
Also for mixins you might consider using [common component](https://github.com/peerlibrary/meteor-blaze-common-component).

**Comment by mitar** [comment]
Also, inside `hookUserIsReady` you can call `this.autorun` normally.

**Comment by thebarty** [comment]
Thanks for your tips.

So I guess the disadvange of using a standard Tracker.autorun() is performance, as the computation is not destroyed when the template is destroyed?

**Comment by mitar** [comment]
Also I think that `currentComponent` (and `currentView`) might not work correctly in non-first runs.

**Comment by thebarty** [comment]
Ok, I'll find a way to make it work with BlazeComponents.autorun(). Thanks for your great work!
