### ISSUE TITLE
TemplateController

### ISSUE THREAD

**Issue by comerc** [peerlibrary/meteor-blaze-components#130]
Please add [TemplateController](https://github.com/meteor-space/template-controller) to "[related projects](https://github.com/peerlibrary/meteor-blaze-components#related-projects)" with yours comments

[Author says](https://crater.io/posts/PWe2DGaKqHRKau3zL):

> Yeah i have used it before – it's also nice, and there are also https://github.com/peerlibrary/meteor-blaze-components. My only "problem" with these existing packages is that they introduce new concepts on top of the standard Blaze api. I just wanted less boilerplate and that best practices like setting up ReactiveVars, validating properties passed to a template or accessing Template.instance() become a no-brainer for the whole team.
> 
> The idea for this package came up during a Meteor training with some Devs where realized how complicated it is to explain the best practices with Blaze and that they had a ton of questions like "how can i access the template instance in helpers / event handlers" or "how does a template manage state" – which is so basic that it should be the easiest thing in the world.

**Comment by mitar** [comment]
Thanks. Added! It seems a really cool project.

I would only add to it inline event binding and then it would be a perfect.

It does not facilitate code sharing and reusability though.
