### ISSUE TITLE
Better debug info on parent component assert fail.

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-blaze-components#132]
One of the hardest things to debug while using blaze components is when the component reports that it's already been rendered. [This assert](https://github.com/peerlibrary/meteor-blaze-components/blob/master/lib.coffee#L787) simply fails and gives you no indication which component failed. It's very cumbersome to try and figure it out by commenting various components out until you find the culprit. Probably a console.log of the current component (if parent exists) prior to assert would be enough to help.

**Comment by mitar** [comment]
Fixed with 5fcfbdaa1c71589de6b117b81c232b95a851e661.

**Comment by mitar** [comment]
One more question, do you find this then to be your bug that this even happens? I would assume this should not be happening to you so often. Why it does?

**Comment by MatejJan** [comment]
Yeah, it's always my bug, but it's one that often happens. It's when you have components in arrays that change and you're rendering them dynamically. It's proving not to be a very easily maintainable coding style so I'm also moving away to better solutions from an architecture standpoint. But still, it happens, and it's hard to figure out.

**Comment by mitar** [comment]
So, is this change I made helping you debug?

So you are keeping instances of components around? And render them multiple times? Yes, I think such use case is less supported. If you have ideas how to make it easier, tell. Maybe we could make it so that if you try to use the same component twice, it forks automatically at that point. But what about the state? Should it be shared or it also gets copied.

**Comment by MatejJan** [comment]
Yeah, I think I've seen it in my console stream by now so it must be working. But like I said, I'm also moving from having reactive lists of components that get rendered (and on reactive rerenders fail), so I don't see it that often.

And yeah, I create child components in a parent component's constructor/onCreated and then render them with helpers. I even made a Render component that saves me from having to write helpers for each component I want to render, but I just pass it as data context to Render component, which does the rendering there.

```
{{> Render someComponentInstance}}
```

But yeah, if that's inside an `{{#each}}` that's an array read from a reactive filed, it runs into problems. I'm probably complicating too much.

And no, forking would not help here, I actually want the same component to be re-rendered. It's just that due to reactivity, it seems the new things try to be added into DOM before the old ones are removed— maybe due to their algorithm of comparing new/old rendering … I have no idea how this works—and there's just this one frame where it's rendered into two places, but will get removed by the flush.

I've had this happen from FlowRouter switches mainly, so maybe the above case is not so much Blaze thing as it's FlowRouter. New route would render before the old one was removed and if it's actually the same route re-rendering the component tries to be added the second time. To get around this I had to add the component on after-flush for example. So it would get removed first and (re)added on the next frame.

So no, the fork/state question is not really applicable to my uses.

**Comment by mitar** [comment]
> Yeah, I think I've seen it in my console stream by now so it must be working.

I have not yet released version with it, I am waiting for you to test it. So if you have not manually update to the latest `git` version then I do not know that you have been seeing. ;-)

If you make a small reproduction of your problem with flow router I could look into it.

**Comment by MatejJan** [comment]
Ah, yeah, now that I think about it, I definitely looked at your source and seen the new message there. I just remember reading it. :) Right now I'm pressed for time, but when I come across the problem next time I'll make a reproduction.
