### ISSUE TITLE
TemplateTwoWayBinding

### ISSUE THREAD

**Issue by comerc** [peerlibrary/meteor-blaze-components#134]
Please add [TemplateTwoWayBinding](https://github.com/comerc/meteor-template-two-way-binding) to "[related projects](https://github.com/peerlibrary/meteor-blaze-components#related-projects)" with yours comments.

**Comment by mitar** [comment]
Sorry, this seems to me solving just one particular thing, and is not a comprehensive rendering solution. I like it, but related projects is not really meant to be a list of everything Blaze related. :-) But things which are similar to Blaze Components.

**Comment by comerc** [comment]
TemplateTwoWayBinding is plugin for TemplateController inspired ViewModel. I choose the best solution 4 months. :)

**Comment by mitar** [comment]
Great. So it should be listed on the TemplateController repository, don't you think?

Make a version for Blaze Components and I will list it here. :-)
