### ISSUE TITLE
Write template HTML within component JS?

### ISSUE THREAD

**Issue by carboniris** [peerlibrary/meteor-blaze-components#141]
Right now I have something like the following:

    template.html

    <template name="foo">
      
    </template>

    component.js

    class FooComponent extends BlazeComponent {
      template () {
        return "foo";
      }
      // some JS here
    }

I'd rather write it like this:

    class FooComponent extends BlazeComponent {
      template () {
        <template name="foo">
          
        </template
      }
      // some JS here
    }

The ability to combine the HTML and JS of a single component in the same place like this is one of the major strengths of JSX and I'm sure would be appreciated by anybody Blaze Components. Perhaps add a Meteor build plugin that just splits the HTML out of BlazeComponents' template attribute and puts it into an HTML file, adding an import in the original JS file?

**Comment by mitar** [comment]
This is being discussed as part of Blaze itself: https://github.com/meteor/blaze/issues/94

The plan is to have:

``` html
<template name="foo">
  <!-- some HTML here -->
</template>

<script>
class FooComponent extends BlazeComponent {
  template () {
    return "foo";
  }
  // some JS here
}
</script>
```

**Comment by mitar** [comment]
So I will be closing this in favor of that.
