### ISSUE TITLE
Values is not defined

### ISSUE THREAD

**Issue by drnickyoung** [peerlibrary/meteor-blaze-components#143]
Hi All,

I know this is me doing something wrong so would appreciate some pointers. I have the demo2 from http://components.meteorapp.com/ set-up, it displays but upon entering a value in the textarea it gives me errors. Specifically onChange gives the error:

`ReferenceError: Values is not defined`

I know what the error means but for the life of me cannot see where in the demo "Values" comes from. I assume I am missing a package somewhere, I swear I ahd the demo working previously. Can anyone point out what stupid mistake I have made?

Nick

**Comment by mitar** [comment]
It is a collection which is available on both client and server side: https://github.com/peerlibrary/meteor-blaze-components/blob/master/demo/lib/demo.coffee

**Comment by drnickyoung** [comment]
Thank you, need glasses, didn't spot that!
Thanks
