### ISSUE TITLE
In-line component creation for lack of method params

### ISSUE THREAD

**Issue by janat08** [peerlibrary/meteor-blaze-components#148]
{{> button attributeDOM newTab href=data.url attribute=data.color attribute="ui button large"}}

So you can just make button with href and expect new tab mixin to open tab instead of redirect for lack of ability to pass in variables to methods inline, but it's just that much easier to make a whole new component.

**Comment by mitar** [comment]
I do not understand what you are asking. You can pass arguments as keyword arguments to a component.

**Comment by janat08** [comment]
you can pass arguments to instance, you can't pass arguments to event method, at which point you want separate instance handling data that event requires.

**Comment by janat08** [comment]
button attributuDOM and newTab being classes here.

**Comment by janat08** [comment]
Oh lol, so {{button arghs mixin='attributeDOM newTab'}}?

**Comment by janat08** [comment]
oh well yea, and then there're actual arguments for method.
