### ISSUE TITLE
Migrating to react: Rendering of BlazeComponents via React is NOT possible

### ISSUE THREAD

**Issue by thebarty** [peerlibrary/meteor-blaze-components#154]
Hi guys,

I made the decision to migrate my project to React - at least to build new features in React from now in.

Meteor Guide mentions https://github.com/gadicc/meteor-blaze-react-component as the way to render Blaze-Templates from a react-component.

BUT when installing `meteor-blaze-react-component` my app crashes with weird errors like 
`Uncaught TypeError: Super expression must either be null or a function, not undefined
`.

In the docs I read that `meteor-blaze-react-component` requires `templating`-package installed, which I think BlazeComponents overwrites or replaces.

Ok, so is there any quick way to do what `meteor-blaze-react-component` does with BlazeComponents?

**Comment by mitar** [comment]
Not sure. I have not used that package.

**Comment by gadicc** [comment]
It was due to a name conflict on the BlazeComponent class.  @duce3 just submitted a PR to fix this, which I've merged and released in v1.4.2.  For more details see https://github.com/gadicc/meteor-blaze-react-component/pull/19.

*This issue can be closed.*
