### ISSUE TITLE
How to use with Blaze.renderWithData() e.g.

### ISSUE THREAD

**Issue by bensmeets** [peerlibrary/meteor-blaze-components#17]
All going great when included with {{> myTemplate}}. Kudos. But my app uses a lot of Blaze.renderWithData to render the state of the app, so no routers.

O couldn't get the BlazeComponent class matching with the template I'm rendering to trigger. Is it possible that I need to do extra actions to kick it off after a Blaze.render().?

**Comment by mitar** [comment]
See the [example here](https://github.com/peerlibrary/meteor-blaze-components/blob/master/tests/tests.coffee#L1194). This API is not yet public and will probably change a bit in the future.

**Comment by bensmeets** [comment]
Will there also be something like Blaze.remove() or something alike? I'm asking, since I like the syntax a lot but need to convert a viewstack-like setup I had running in normal Blaze. I dynamically create and destroy views by Blaze.renderWithData() and Blaze.remove(). Curious if that is possible with purely components as well (or will be maybe).

**Comment by mitar** [comment]
Interesting idea. You can see [how I am using Blaze.remove](https://github.com/peerlibrary/meteor-blaze-components/blob/master/tests/tests.coffee#L1248) here. But you are probably right that we should abstract this out.

**Comment by mitar** [comment]
I opened #36.
