### ISSUE TITLE
Seeking help from a native English speaker

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#22]
I think the documentation and demo app text content would benefit from a native English speaker going over it and fix things. :-)

**Comment by offthegrass** [comment]
I'll be happy to contribute when I have a better understanding of the package.

**Comment by Sivli-Embir** [comment]
Not sure how much help I can be on English syntax, human languages baffle me, but [class methods docs](https://github.com/peerlibrary/meteor-blaze-components#reference) could be cleaned up:

``` coffee
#from
componentChildren: ([nameOrComponent]) ->
#to
@componentChildren([nameOrComponent])
```

The current docs took me a minute to realize it was a function that exists and I could call, and I use coffee daily. At first I though it was some strange injection/mixin magic.

**Comment by mitar** [comment]
OK, this should really go into a separate ticket. But OK. :-)

Please propose the whole syntax. Because you have both the class methods and instance methods. Currently class methods have the `@` prefix. Instance do not.

But isn't the above the CoffeeScript syntax for methods? Why it is confusing?

**Comment by rclai** [comment]
I would help but I am still digesting this package.

**Comment by mitar** [comment]
No problem. :-) This is why they are tickets. So that we have a list of things that has to be done. :-)

Also, at this stage it is useful to learn what things are not yet explained good enough.

**Comment by Siyfion** [comment]
If it's just grammatical, spelling and sense-checking of the docs that you want, I'd be more than happy to go over it?

**Comment by mitar** [comment]
Any help would be welcome. :-)
