### ISSUE TITLE
Components in packages: dependencies 

### ISSUE THREAD

**Issue by offthegrass** [peerlibrary/meteor-blaze-components#23]
is there anything to prevent the following from working? (where **app** is the only package installed using `meteor add`, and the others are added via dependencies) 

**BUTTON-BASE**

```
/packages/button-base/button-base.coffee

class buttonBase extends BlazeComponent
    @register 'buttonBase'
....

```

**ANOTHER-BUTTON**

```
/packages/another-button/package.js

api.use([
        'button-base'
    ])

```

```
/packages/another-button/another-button.coffee

class anotherButton extends buttonBase
    @register 'anotherButton'
```

**APP**

```
/packages/app/package.js

api.use([
        'another-button'
    ])

```

Currently I'm getting this error:

```
Uncaught ReferenceError: buttonBase is not defined
```

I assume it's a load order issue?

**Update:** I copy and pasted one of the demos into a single file (components.coffee) in a barebones hello meteor app, which of course works. But if I split it into two files (componentOne.coffee componentTwo.coffee), I get the same issue. 

I've been through the tutorial and looked over the docs again, and it's not clear what the problem is...

> You do not have to export [classname] from your package for components to be available in templates throughout your project. The registry of components is shared between all packages and the project. 

What am I missing?

**Comment by mitar** [comment]
You should or:
- export the `buttonBase` symbol using `api.export` in the `button-base` package
- you use Blaze Components registry to access the `buttonBase` component:

```
class anotherButton extends BlazeComponent.getComponent 'buttonBase'
    @register 'anotherButton'
```

**Comment by mitar** [comment]
If you split the code into two files inside a package, and do not export a symbol, you should use `share.` prefix to make symbols available inside whole package:

```
class share.buttonBase extends BlazeComponent
    @register 'buttonBase'
```

```
class share.anotherButton extends buttonBase
    @register 'anotherButton'
```

BTW, here is nothing special about Blaze Components. This is simply [how symbol sharing and exporting works in Meteor](http://docs.meteor.com/#/full/coffeescript). The only additional thing is the `BlazeComponent.getComponent` thingy.

**Comment by offthegrass** [comment]
I ended up using api.export / .share but I knew I was missing something.  

`BlazeComponent.getComponent` was the missing link - thanks.

**Comment by mitar** [comment]
See [this section](https://github.com/peerlibrary/meteor-blaze-components#namespaces) on a bit of discussion about this topic.

**Comment by offthegrass** [comment]
yeah I did read that; I hadn't considered that you could use `getComponent` in the extend function!

most of the examples use the pattern `class SomeClass extends BlazeComponent`, so it wasn't immediately apparent that you can change it. makes sense now though.

In the docs:

> Even if you need to access a component's class in your code, you can use 
> 
> `BlazeComponent.getComponent('Buttons.Red')` to access it

Add something like this below?

E.g. 
`class AlertButton extends BlazeComponent.getComponent('Buttons.Red')`
