### ISSUE TITLE
Q: Using mixin methods

### ISSUE THREAD

**Issue by offthegrass** [peerlibrary/meteor-blaze-components#24]
I'm trying to call a mixin method as per the docs. 

Code: 

```
class MyComponent extends BlazeComponent
    @register 'MyComponent'

    template: ->
        'MyComponent'

    mixins: ->
        [BlazeComponent.getComponent 'MyMixin']

    events: -> [
        'click button': @onClick 
    ]

    onClick: ->
        @callFirstWith null, 'clickHandler'
```

```
class MyMixin extends BlazeComponent
    @register 'MyMixin'

    clickHandler: ->
        console.log 'ive been clicked'
```

If an event handler is set inside the mixin, i.e. `'click button': @clickHandler` where the button is inside `MyComponent`, it works as expected. 

I can also access `@mixinParent()`, so it appears to be set up correctly. 

However if I try to call the `clickHandler` method from the parent, it is undefined.

`Uncaught TypeError: undefined is not a function`

**Comment by offthegrass** [comment]
if I add a `templateHelper` to the mixin

```
aMessage: ->
    'I am a helper'
```

I can use `{{aMessage}}` inside the `MyComponent` template to display `I am a helper` without calling anything. 

>  You can think of a component just like you would of a template, except the functionality (helpers and events) are defined through a class.

This makes sense - it looks for the `aMessage` helper (method) inside the component. If it doesn't find it, it looks through the mixins in the order that they are listed until it finds it. 

If I wanted to use a method from another file in meteor, I might define it like this: 

```
@Example = {}
@Example.function = (text, callback)  ->
    console.log text
    callback 'function completed'
```

or something like

```
share.Example.function = 
....
```

and call it like this: 

```
Example.function 'hey', (result) ->
    console.log result
```

I don't want to be defining global methods for each mixin, but if I did, I can't because:

> In normal template helpers @ refers to the data context
> In Blaze Components @ always refers to the component instance

Isn't the whole point of a mixin that you can define your methods inside, and use those methods from a component? 

From inside a component, shouldn't I be able to do 

```
aFunction: ->
    return aMessage
```

as long as the component has a mixin with the `aMessage` helper? Similar defining methods with `Meteor.methods` and then calling them with `Meteor.call`?

I can see the powerful potential of BlazeComponents, and I really want to experiment, but at the minute I feel like this is elementary stuff I'm stuck at an invisible wall. 

Either: 

a) Using BlazeComponents is no different to using vanilla meteor. There are new features; as long as you're competent w/ meteor, it will be easy to understand.

b) Using BlazeComponents is slightly different to using vanilla meteor, e.g. it adds the ability to use helpers as methods. BlazeComponents mainly build on coffeescript classes, so you need to understand how to use coffeescript classes in order to fully understand BlazeComponents.

c) BlazeComponents shares some syntax from vanilla meteor, and adds a lot of its own. Forget what you know about meteor while learning BlazeComponents. 

d) I'm an idiot

**Comment by mitar** [comment]
> However if I try to call the clickHandler method from the parent, it is undefined.

It seem this is caused if you use 0.1.0 version. Which is for some reason the default version Meteor adds if you do `metor add peerlibrary:blaze-components` (any idea how to fix this?). If you upgrade to latest version your example [works](http://meteorpad.com/pad/eaXwrcxYqGJZ9s3iE/Leaderboard). (I could not select the latest version in meteorpad either, but it is newer than 0.1.0.)

**Comment by offthegrass** [comment]
worst bug ever

same if you add the package via api.use. I never would have found that.

to anyone who is reading this: just run `meteor update`, or if you're using it in a package, write `api.use('peerlibrary:blazecomponents@0.7.0')`
