### ISSUE TITLE
Allow mixins to configure which template is used

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#26]
As discussed in [this ticket](https://github.com/peerlibrary/meteor-blaze-components/issues/25#issuecomment-94958384), it would be maybe useful to allow mixins to configure whcih template is used. This would allow for an existence of a mixin component authors could use to make others replace the template with some other official (instead of overriding `template` class method on prototype).

**Comment by Sivli-Embir** [comment]
:+1:
