### ISSUE TITLE
Template.dynamic is causing an infinite loop

### ISSUE THREAD

**Issue by mquandalle** [peerlibrary/meteor-blaze-components#30]
I try to include a template (not a _component_) from a blaze-component using `{{> Template.dynamic}}`, but it causes an infinite loop.

Here is a minimal reproduction: https://github.com/mquandalle/blaze-components-template-dynamic. In this example commit-1 is working fine, and then after I transform my template into a blaze component in commit-2 there is an infinite loop.

**Comment by MatejJan** [comment]
I was just about to open this ticket too. :)

**Comment by MatejJan** [comment]
A workaround that was sufficient for my case of

```
{{> Template.dynamic template=someTemplateName}}
```

(where `someTemplateName` was a property on the inner data context), was to go with

```
{{> someTemplate}}
```

and in component I have

```
someTemplate: ->
  Template[@currentData()?.someTemplateName] or null
```

**Comment by mitar** [comment]
Of course, this is even better because an inherited component can then change the behavior if wanted. :-)

But yea, this should be fixed.

**Comment by mitar** [comment]
Thanks for reporting.
