### ISSUE TITLE
Issue with componentChildren and inherited components

### ISSUE THREAD

**Issue by Sivli-Embir** [peerlibrary/meteor-blaze-components#32]
I have the following setup. See comments

``` coffee
class @FormComponent extends BlazeComponent
  @register 'FormComponent'
  template: -> 'FormComponent'
  ...

class @ExampleComponent extends FormComponent
  @register 'ExampleComponent'
  template: -> 'ExampleComponent'
  onRendered: -> #my issue is here
    for input in @componentChildren()
      console.log input #logically this should be only the children
  ...
```

``` jade
//- sorry for the jade, but it may be the cause so I left it unconverted
template(name='ExampleComponent')
  form
    +InputComponent.Text name='name'
    br
    +InputComponent.Checkbox name='bool'
    br
    input(type='submit' disabled='{{isInvalid}}') 
```

This returns Text, Checkbox and _ExampleComponent_!

**Comment by Sivli-Embir** [comment]
``` coffee
class @InputComponent extends BlazeComponent
  @register 'InputComponent'
  template: -> 'InputComponent'
  InputComponent: true #identifier, inherited

class @FormComponent extends BlazeComponent
  @register 'FormComponent'
  template: -> 'FormComponent'
  getInputs: -> @componentChildrenWith 'InputComponent' #get by identifier

class @ExampleComponent extends FormComponent
  @register 'ExampleComponent'
  template: -> 'ExampleComponent'
  onRendered: -> #my issue was here
    for input in @getInputs()  #inherited
```

This resolves the issue and is likely a safer choice anyway. That said I believe this is still a bug.

**Comment by rclai** [comment]
Oh so essentially `componentChildren()` is supposed to return only child components of `ExampleComponent` and not `FormComponent` in the first post, right?

**Comment by Sivli-Embir** [comment]
@rclai  Right, the idea was FormComponent has a bunch of nice setup logic but you use ExampleComponent, or whatever, to wire up a form. But I was getting back ExampleComponent... which is really odd to me. 

I also am seeing other issues now. I hope I am doing something very foolish.

``` coffee
class @FormComponent extends BlazeComponent
  ...
  events: -> [ 'submit': @onSubmit ]
  onSubmit: (e, t) -> 
   console.log @
   @save()
  save: -> console.log 'form'

class @ExampleComponent extends FormComponent
  ...
  save: -> console.log 'example'
```

The `onSubmit` logs my root component, which is above FormComponent in the html, and `"form"`! So confused.

**Comment by mitar** [comment]
Can you make please a complete reproduction? A repository?

**Comment by Sivli-Embir** [comment]
That's my intent. Too much is not working.

**Comment by rclai** [comment]
Could it be the version of Meteor?

**Comment by mitar** [comment]
> `onSubmit: (e, t) ->`

BTW, Blaze Components do not get a template as a second argument.

**Comment by mitar** [comment]
I cannot reproduce this. I tried with:

``` coffee
class @FormComponent extends BlazeComponent
  @register 'FormComponent'
  template: -> 'FormComponent'
  events: -> [ 'submit': @onSubmit ]
  onSubmit: (e) ->
   e.preventDefault()
   console.log @
   @save()
  save: -> console.log 'form'

class @ExampleComponent extends FormComponent
  @register 'ExampleComponent'
  template: -> 'ExampleComponent'
  save: -> console.log 'example'
```

``` handlebars
<body>
  {{> ExampleComponent}}
</body>

<template name="ExampleComponent">
  <form><input type="submit"></form>
</template>
```

And when I click submit, I get:

```
ExampleComponent {}
example
```

Which I think is exactly as expected, no?

**Comment by Sivli-Embir** [comment]
!!! Yes that is exactly what is expected. I will definitely get set up a repository. It will be good to see how to cause my issue.

**Comment by mitar** [comment]
Also, I did:

``` coffee
class @ExampleComponent extends FormComponent
  @register 'ExampleComponent'
  template: -> 'ExampleComponent'
  save: -> console.log 'example'

  onRendered: ->
    for input in @componentChildren()
      console.log input

class InputComponent

class InputComponent.Text extends FormComponent
  @register 'InputComponent.Text'
  template: -> 'InputComponent.Text'

class InputComponent.Checkbox extends FormComponent
  @register 'InputComponent.Checkbox'
  template: -> 'InputComponent.Checkbox'
```

``` handlebars
<template name="InputComponent.Text">
  <p>InputComponent.Text</p>
</template>

<template name="InputComponent.Checkbox">
  <p>InputComponent.Checkbox</p>
</template>

<template name="ExampleComponent">
  <form>
    {{> InputComponent.Text}}
    {{> InputComponent.Checkbox}}
    <input type="submit">
  </form>
</template>
```

And I get in the console:

```
Text {}
Checkbox {}
```

Also what I would expect.

**Comment by mitar** [comment]
Do you by any chance use Polymer for the `InputComponent.Checkbox` implementation? Maybe that's the cause?

**Comment by mitar** [comment]
Did you resolved the issue? Find a reproduction? Do you have an example code which fails as you are describing?

**Comment by Sivli-Embir** [comment]
@mitar sorry this took me so long. I found where it was coming from. It seems my onSubmit event is calling twice. Once from the example component and once with my root component as the context `this`. Very odd. I have made reproduction repo here https://github.com/Kestanous/form-component. The issue is console logged [here](https://github.com/Kestanous/form-component/blob/master/client/components/%24form/form.coffee#L14).

**Comment by mitar** [comment]
So your `HomeComponent` extends `FormComponent`. And your `FormComponent` has a `submit` event handler defined. So what is surprising here? You register `submit` event handler on two components. And then normal DOM event propagation does the rest. First event triggers `submit` in `FormComponent` and then it propagates up and finds `HomeComponent`, and it triggers event handler again.
