### ISSUE TITLE
Q: passing attributes (via args?)

### ISSUE THREAD

**Issue by offthegrass** [peerlibrary/meteor-blaze-components#33]
I want to write something like this in my app:

```
{{> MyComponent shadow disabled}}
```

and something like this in my component template: 

```
<my-component {{attr}}></my-component>
```

with the output being

```
<my-component shadow disabled></my-component>
```

what's the best way to do this? can I do it without the use of a helper, like I can if I write `class='{{name}}'`  in the helper and `class='{{class}}'` in the template?

It's not clear how to use `args`, especially if you haven't used `Spacebars.kw({key: 'xyz'})` before!

**Comment by Sivli-Embir** [comment]
:+1: I have been meaning to learn how to pull that off as well.

**Comment by mitar** [comment]
Untested, but maybe something like this?

``` coffee
MyComponent extends BlazeComponent
  @register 'MyComponent'

  template: ->
    'MyComponent'

  constructor: (args...) ->
    @attrs = {}
    for arg in args
      if arg instanceof Spacebars.kw
        _.extend @attrs, arg.hash
     else
        @attrs[arg] = ''
```

``` handlebars
{{> MyComponent args 'shadow' 'disabled'}}
```

**Comment by mitar** [comment]
BTW, a question is also if you want to pass this through arguments, or would it be better through a data context. Because through arguments will recreate a component if arguments change. And through data context would just modify them in place, while keeping the rest. I am not sure how Polymer reacts to this? Reactively? If you modify attributes on an already created a component?

So maybe you want:

``` handlebars
{{> MyComponent shadow='' disabled=''}}
```

``` handlebars
<my-component {{data}}></my-component>
```

**Comment by offthegrass** [comment]
thanks, I'll use the `{{data}}` method.

I'm not using Polymer... or are you just curious?

**Comment by offthegrass** [comment]
Instead having to always include `=''`, would it be possible to  parse something like `(shadow)` or `-shadow` into `shadow=''` before it gets processed?

**Comment by mitar** [comment]
That is something you should open a ticket with Meteor. :-) How Spacebars templates are parsed.

In meantime you could create a global template helper:

``` handlebars
{{> MyComponent attrs 'shadow' 'disabled'}}
```

``` coffee
Template.registerHelper 'attrs', (args...) ->
  attrs = {}
  for arg in args
    if arg instanceof Spacebars.kw
      _.extend attrs, arg.hash
    else
        attrs[arg] = ''
  attrs
```

**Comment by mitar** [comment]
> I'm not using Polymer... or are you just curious?

That was the question in your ticket about issues with `componentChildren` and events propagation. Maybe there is some bad interaction with Polymer.

**Comment by offthegrass** [comment]
got it:

```
{{> MyComponent attr='shadow disabled'}}

attributes: ->
    attr = @data().attr.split(' ')
    res = {}
    for a in attr
      res[a] = ''
    res

<my-component shadow disabled></my-component>
```

**Comment by mitar** [comment]
I think this is a bit error prone. :-) `{{> MyComponent attr='class="foo bar"'}}` :-)

I do not think splitting is a good API.
