### ISSUE TITLE
Q: Why must a component have to be registered yet also include a template method?

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-blaze-components#35]
If these two things are almost always the same, is there an occasion why we would make them different from each other?

**Comment by mitar** [comment]
The rationale here was that you can reuse the same template multiple times.

``` coffee
class MyComponent extends BlazeComponent
  @register 'MyComponent'

  template: ->
    `MyComponent`

class OurComponent extends MyComponent
  @register 'OurComponent'
```

See, the second time we are reusing the template from the first one.

BTW, you do not have to register components to use them. You have to register them only if you want to be able to directly include them in the template using `{{> ...}}` syntax. If you are including them using methods on existing components, then you can just return them there.

One more thing. You can also create your own default, if you want:

``` coffee
class MyComponent extends BlazeComponent
  @register 'MyComponent'

  template: ->
    @componentName()

class OurComponent extends MyComponent
  @register 'OurComponent'

  template: ->
    # A special case, we do not use 'OurComponent' template.
    'SpecialTemplate'
```

I think a good question is if maybe a default implementation of `template` method should not be just `@componentName()`. :-)

**Comment by rclai** [comment]
I just ran into a use case of using the same template and registering different components. Now I see why this is useful.

**Comment by mitar** [comment]
But I think we should make `template` by default resolve to `@componentName()`, no?

**Comment by rclai** [comment]
Oh, yes that would be a good idea.

**Comment by Sivli-Embir** [comment]
:+1:

**Comment by rclai** [comment]
Sweet, thanks. Are you going to publish to Atmosphere?

**Comment by mitar** [comment]
Yes. I am working on few others tickets first.

**Comment by rclai** [comment]
Cool.

**Comment by rclai** [comment]
Upgraded!
