### ISSUE TITLE
Arguments / constructor

### ISSUE THREAD

**Issue by offthegrass** [peerlibrary/meteor-blaze-components#37]
with this example from the demo:

```
mixins: -> [
  ....
  new StorageMixin Values, 'value', => @data().id
]
```

```
class StorageMixin extends BlazeComponent
  constructor: (@collection, @fieldName, @selector) ->
```

I would like to change 

```
new StorageMixin Values
```

to something like

```
new StorageMixin @data().collection
```

so I can do 

```
{{> MyComponent collection='Values'}}
```

I do want the component to re-render if the collection changes, so do I use args in the MyComponent constructor? what is the correct way to do this?

**Comment by offthegrass** [comment]
```
{{#MyComponent args collection='Values'}}
```

```
constructor: (args) ->
        @collection = eval(args.hash.collection)
```

this works.

**Comment by mitar** [comment]
Why `eval` there? This looks really wrong, strange, unnecessary?

**Comment by rclai** [comment]
Use `window[args.hash.collection]` instead dude.

**Comment by mitar** [comment]
Oh, you want to access a global symbol? Oh. :-)

I prefer then putting in the top level of a file:

```
globals = @
```

And then you can use `globals[args.hash.collection]`.

**Comment by mitar** [comment]
You could also use: https://github.com/dburles/mongo-collection-instances

**Comment by offthegrass** [comment]
thanks for the tips. that package looks useful.
