### ISSUE TITLE
Extend with base template as well

### ISSUE THREAD

**Issue by bensmeets** [peerlibrary/meteor-blaze-components#38]
Still trying to wrap my head around the whole concept, so bare with me if these are silly questions :)

I have my (mentioned earlier) Viewstack setup working in BC (Blaze-Components) now. And apart from an untrackable "must be attached" exception from somewhere deep within Blaze itself, everything is going fine.

So when I wanted to go the next step, I started thinking about "extend" in BC. It means the class itself, I get that. But what are the current thoughts about the template in the parent? E.g., Let's say I have a BC called ParentComponent, which has a template associated with it. In that template I could render all "chrome" for that component. Then if I want to create ChildComponent, I only want to add specific content for that Child without having to copy all the html from the ParentComponent.

In classic Blaze, I did something similar with:

```
<template name="Child">
  {{#wrapper}}
    My child content
  {{/wrapper}}
</template>
```

**Comment by mitar** [comment]
So one thing you might want to use is components as [block helpers](https://github.com/peerlibrary/meteor-blaze-components#component-based-block-helpers). It goes also a bit into making more custom components which can be dynamically controlled what to render.

But if you would like to do something more like you are approaching it above, you could do something like:

``` handlebars
<template name="Parent">
  <div class="parent">
    {{> childTemplate}}
  </div>
</template>

<template name="Child">
  <p>Child</p>
</template>
```

``` coffee
class Parent extends BlazeComponent
  template: ->
    'Parent'

  childTemplate: ->
    null

class Child extends Parent
  childTemplate: ->
    Template.Child
```

So in general, if you want to insert content inside a parent component, then parent component have to provide some placeholder where you want to do that. Wrapping parent component with more stuff is easier.

``` handlebars
<template name="Parent">
  <p>Parent<p>
</template>

<template name="Child">
  <div class="child">
    {{> parentTemplate}}
  </div>
</template>
```

``` coffee
class Parent extends BlazeComponent
  template: ->
    'Parent'

class Child extends Parent
  template: ->
    'Child'

  parentTemplate: ->
    Child.__super__.template.apply @
```
