### ISSUE TITLE
Access to "view"

### ISSUE THREAD

**Issue by bensmeets** [peerlibrary/meteor-blaze-components#39]
Acces to "view": I'm already having trouble with everything related to views/templates/templateinstances and what not, I hoped the components wouldn't add to that list but abstract it all away. That maybe coming in the future. But until then I found that the only way to access the view the component is related to was through _componentInternals. Maybe something like a "getView" on the component? Preference is to abstract it away though :)

**Comment by mitar** [comment]
Care to explain why you need access to `view`? I hopped I already abstracted all use cases away. :-) And that you would not have to think about template instances and views at all anymore.

**Comment by bensmeets** [comment]
Sure, it's because of the Blaze.remove() as mentioned here #36 . I wanted to be helpfull and group some feedback in the Q&A thread, but as I respond now I guess it's making a bit of a mess of the issues :).

So plz remove if needed.

**Comment by mitar** [comment]
I still do not get you. You render manually and you cannot keep the `view` object around, so you would like to be able to get it yourself from the component later on again?

**Comment by bensmeets** [comment]
Yes, but just to be able to pass it on to Blaze.remove(). I use componentChildren() to find out all existing "panels" inside a viewstack component of mine. Having the component works, than just need to get the view of that component to be able to remove it once I click a "close" like button from within that panel.

**Comment by mitar** [comment]
Hm, should this be `BlazeComponent.remove(componentInstance)` or `componentInstance.remove()`? :-)

**Comment by bensmeets** [comment]
instance.remove() has a nice feel to it. Makes more sense to me than BlazeComponent.remove() which only has going for it that it matches Blaze, but Blaze has no (apparent) parent/child relationships to factor in (as far as I know). Calling remove on the parent is more specific.

**Comment by bensmeets** [comment]
On reading it again, I didn't get your comment correctly. There is one more (which I thought you meant):
- calling parentInstance.remove(childInstance);

**Comment by mitar** [comment]
Yes. I thought more like `instance.removeItself()`.

Good idea to remove children.

**Comment by mitar** [comment]
But probably it is better to remove itself, because you can always first access the child though `componentChildren`. Otherwise one  cannot remove the root itself.

**Comment by bensmeets** [comment]
true. sounds good!

**Comment by mitar** [comment]
Implemented as `instance.removeComponent()`.
