### ISSUE TITLE
Q: What about global helpers?

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-blaze-components#40]
Global helpers don't work in components, which might be a problematic. I wonder if by default `BlazeComponent` should inherit all global helpers? Not sure what the best solution is to this, so what I did was create a super base BlazeComponent that essentially just encapsulates all global helpers and then created components that extend off of it so that I can use the global helpers:

``` js
Components.BaseComponent = BlazeComponent.extendComponent(Blaze._globalHelpers);
```

**Comment by mitar** [comment]
Global helpers should work in components. Only that they have a normal Blaze `this` binding. So `this` is current data context and not the component. If you want to get access to the component inside a normal template helper (including a global template helper), you can do `Template.instance().component`.

This is related to #18. We should provide a way to create a global template helper which has by default correctly bound `this`.

> Not sure what the best solution is to this, so what I did was create a super base BlazeComponent that essentially just encapsulates all global helpers and then created components that extend off of it so that I can use the global helpers:

This is the craziest tricky I have seen in a while. :-) Amazing.

**Comment by rclai** [comment]
Lol yea it was insane but actually I think it is going to backfire because there's a global helper $ from the handlebar helpers package that overrides the template instance method for jQuery querying I think.

**Comment by mitar** [comment]
Really? This is the first time I heard about it. And what is the use for it?

**Comment by rclai** [comment]
It's to register custom global variables as global templates helpers. For example, you can register the console object and you can essentially console log in your templates. 

{{$.console.log 'hello world'}}
