### ISSUE TITLE
Removing child doesn't trigger reactivity?

### ISSUE THREAD

**Issue by bensmeets** [peerlibrary/meteor-blaze-components#42]
Not sure about this, but trying to link a child to a parent by reacting on a "this.componentChildren" count. It seems it's triggered when adding child components, but not when removing them. After checking manually, the child is removed though. The reaction just doesn't fire. Or is it me :)

**Comment by mitar** [comment]
Please create a reproduction.

**Comment by bensmeets** [comment]
I've been trying to reproduce in a seperate project. But for the life of me I can't get it to bind anymore. I'm guessing it's because of something weird I did in my code in other places and/or from my missing understanding of bindings sometimes.

it came down to something like this:

```
Parent {
  count: function() {
     return this.componentChildren().length;
  }
}

Child {
  render: function() {
    var count = this.componentParent().count();
    this.setOpacity(count);
  }
}
```

Once upon a magic time, that bottom "render" function was called when I added something from the Parent, but not when I removed something from that same parent. But having it in a seperate project, that render function never gets called. Will update if I come across it again sometime.

**Comment by mitar** [comment]
I am unsure now. So are you saying that it works now or that it does not work?

**Comment by bensmeets** [comment]
I'm just as unsure ;) I think it is not triggered when the number of children reaches 0. Again, this is most likely to do with my lack of grasping the reactivity in general, but just wanted to be sure. 

Took a while, but I have an example available in Meteorpad http://meteorpad.com/pad/2jtx4uBREgBDnWT3A/Leaderboard although it won't run in Meteorpad itself, because of an error with the BC package. Add a few items by clicking, then remove each and look at the console. It won't log anything when children reach 0.

**Comment by mitar** [comment]
It works as expected. See [this fork](http://meteorpad.com/pad/F32gtrqMm2t3R6CWw/Copy%20of%20Leaderboard).

The issue you are having is that when component is destroyed, `autorun` is stopped. And component is destroyed before it is removed from the parent. So first the component is destroyed, and then it is removed from the parent, so just after that the count changes. If you look at the count from the parent's point of view, you will see that it reaches 0.

BTW, you can explicitly add `0.8.0` version of Blaze Components to the Meteorpad if you do not just select from the autocomplete choices, but write the whole string in. `peerlibrary:blaze-components@0.8.0`.
