### ISSUE TITLE
Q: AutoForm breaks?

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-blaze-components#46]
Putting an autoform inside a component is gonna break isn't it?

**Comment by mitar** [comment]
It should not. Why it would? What do you have in mind?

**Comment by rclai** [comment]
I got this error when I tried embedding an autoform inside a component:

```
Exception in template helper: TypeError: Cannot read property 'class' of undefined
    at Object.addClass (http://dev.profab.io:3003/packages/aldeed_autoform.js?e71f561d26e90711b8a4ddf6136073fdffff296d:624:20)
    at attsPlusFormControlClass (http://dev.profab.io:3003/packages/aldeed_autoform.js?e71f561d26e90711b8a4ddf6136073fdffff296d:7928:27)
    at http://dev.profab.io:3003/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1651:16
    at http://dev.profab.io:3003/packages/peerlibrary_blaze-components.js?2c973af5894c7300f73f65b2ab04d3073485a5a5:319:66
    at Function.Template._withTemplateInstanceFunc (http://dev.profab.io:3003/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at http://dev.profab.io:3003/packages/peerlibrary_blaze-components.js?2c973af5894c7300f73f65b2ab04d3073485a5a5:318:27
    at Spacebars.call (http://dev.profab.io:3003/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
    at Spacebars.mustacheImpl (http://dev.profab.io:3003/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:25)
    at Object.Spacebars.attrMustache (http://dev.profab.io:3003/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:125:39)
    at http://dev.profab.io:3003/packages/aldeed_autoform.js?e71f561d26e90711b8a4ddf6136073fdffff296d:9427:22
```

I don't know if it has anything to do with it trying to access the data context the wrong way?

The autoform looks like this:

``` html
{{#autoForm id='myform' type='insert' collection='Items'}}
    {{> afQuickField name='field1' class="form-control"}}
    {{> afQuickField name='field2' class="form-control"}}
    <button class="btn btn-primary">Save</button>
{{/autoForm}}
```

This form worked when I put it in a regular non-component template. This is also using the latest version of autoform.

**Comment by rclai** [comment]
Found the underlying problem, it is a currentData issue:

https://github.com/aldeed/meteor-autoform/blob/6273c7f9a54acf85596a4a641c050951c5ef92a5/templates/bootstrap3/bootstrap3.js

**Comment by mitar** [comment]
Can you explain a bit more? I do not get it from the link you pasted?

**Comment by rclai** [comment]
Autoform uses global helpers to populate the attributes of the form input elements, but because the autoform is embedded inside a component, the `this` is that of a component and not of a regular template, and therefore `this.atts` will be undefined.

**Comment by mitar** [comment]
No. Inside a normal global template helper `this` points to a data context.

**Comment by mitar** [comment]
(Except if you are doing some trick like you are describing in #40.)

**Comment by rclai** [comment]
But in my case, it is not. I stepped through it in the debugger, and saw that `this` is the component instance inside that global helper.

Another piece of information is that the component that the autoform is in was rendered via `Template.dynamic`, so I don't know if that changes things.

**Comment by mitar** [comment]
Can you make a small reproduction? So just one component having an autoform as content?

**Comment by rclai** [comment]
Oh, the trick, let me check.

**Comment by mitar** [comment]
In that case you should just remove `attsPlusFormControlClass` and `attsPlusBtnClass` from your component prototype, so that they are resolved as global helpers and not component methods.

**Comment by rclai** [comment]
Yup you were right that was the issue.
