### ISSUE TITLE
Q: Parent/child subscriptionsReady

### ISSUE THREAD

**Issue by bensmeets** [peerlibrary/meteor-blaze-components#47]
I could use some education on what think-errors I'm making with the setup below. I think the core is that I'm trying to approach everything in OOP, but that that is not the complete way BC is set up (maybe). e.g:

I have a base component, which doesn't do much. I use it to encapsulate all kind of things for all extended instances. Enabled/visible, that kind of stuff.

```
BasePanelComponent = BlazeComponent.extendComponent({});
```

From this base, I create instances like so:

```
InstancePanelComponent = BasePanelComponent.extendComponent({
  template: function() {
    return "InstancePanelComponent";
  },
  onCreated: function() {
    this.subscribe('getEverything');
  }
}).register("InstancePanelComponent");
```

They do a bit more and handle their own subscriptions and so fort. 

In the respective template, I used a bit of unsupported syntax (I think) but it seemed to work ok. Like so:

```
<template name="BasePanelComponent">
  {{#if subscriptionsReady}}
    All done loading!
  {{/if}}
  {{> Template.contentBlock}}
</template>

<template name="InstancePanelComponent">
  {{#BasePanelComponent}}
    Anything...
  {{/BasePanelComponent}}
</template>
```

Now the challenge, it seems the "subscriptionsReady" is not acting. I'm guessing because the Instance is the one making the subscriptions and not the base, so base knows nothing about these subscriptions. So should I tackle the above differently _or_ is there a way to access the subscriptionsReady with maybe a slightly different call, from the "instance".

**Comment by rclai** [comment]
You need to use Template.contentBlock.

**Comment by bensmeets** [comment]
Right, forgot to add that to my snippet, but I have it in my code. Added it to the example. But stil not possible to access the "Instance" function from the "Base".

**Comment by rclai** [comment]
I think because you're in the parent component you need to get access to the child component to check subscription status.

**Comment by mitar** [comment]
I think your issue is that you are mixing extending the component with block helpers. And this is getting you confused. You use both the base component and extended component in your template. Which effectively means that you are doing something like:

``` handlebars
<template name="ComponentB">
  {{#ComponentA}}
    Anything...
  {{/ComponentA}}
</template>
```

If we ignore for a moment that you implemented `ComponentB` and `ComponentA` through inheritance, in your template you simply have two components working together. One component uses another as block helper. If would be easier to imagine something like that maybe:

``` handlebars
<template name="ComponentB">
  {{> ComponentA args content='Anything...'}}
</template>
```

So how does `ComponentA` access `subscriptionsReady` of `ComponentB`? In fact, `ComponentB` is a child of `ComponentA`. So, as @rclai said, you should use `parentComponent`.

The fact that you implemented `ComponentA` and `ComponentB` through inheritance does not influence at all how you are using the components. You are using components as child-parent (through block helpers).

**Comment by bensmeets** [comment]
Great! Thanks for the thorough explanation. I get it. Live and learn.

Could this (funky) setup I use impact the "onRendered" of the ComponentA in this example? I'm having trouble getting it called when ComponentB is rendered. Even though, I'm calling **super** from componentB. If it shouldn't impact it, I need to debug further :)

**Comment by mitar** [comment]
I must say that I do not follow what you are doing anymore. :-) It is too complicated. There is no reason why things should not be called though.

**Comment by bensmeets** [comment]
yeah I totally get it, I had a hunch I'm creating chaos here :). I think the onRendered trouble is starting, because I'm also adding it to another "Stack" component. Let's see if I can compress my example a bit.
1. I have a component called "ViewStack".
2. I have a component called "ViewStackPanel".
3. I have "instances" of the ViewStackPanels which extend ViewStackPanel as a class, but at the same time uses it inside itself as a blockhelper. Like the componentB class above.

```
DashboardPanel = ViewStackPanel.extendComponent({
  // Do stuff specific for this instance, but allow for reuse of all things defined in the
  // ViewStackPanel class as well.
});

<template name="DashboardPanel">
  {{#ViewStackPanel}}
    <!-- My specific dashboard stuff -->
  {{/ViewStackPanel}}
</template>
```

4 Through logic in "ViewStack" class (top level) I add instances to the ViewStack as children. E.g., I add a new DashboardPanel to ViewStack. So it's one big spaghetti of classes and block helpers :)

I have this setup, so I have 1 place to define the look and feel (and logic) of each panel, and make the contents of each panels (and logic) seperate at the same time.

That's where I'm guessing I'm making the error. And I think it all boils down to the fact that I am using the ViewStackPanel as a block helper, since there is no other way I can think of to compose the "super" and "instance" templates otherwise. I think something needs to "click" in my brain a bit more :)

**Comment by bensmeets** [comment]
This is a nice summary on how I have this setup running. It includes a simpler version of how I dynamically add nodes to the "ViewStack". In this example, I just use onRendered in ViewStack for that, but the principle is the same in my real world code.

http://meteorpad.com/pad/YvcCX7HH29ahYhd5A/Viewstack

In this example, onRendered s called everywher _just as it should an is expected_. So there is something in my own code that is making it nog trigger. Will investigate further :) Thanks for the help.

edit: I've added a bunch of comments to the MeteorPad, trying to explain the rationale behind this weird setup of mine.

**Comment by mitar** [comment]
No, I think your setup could be viable, just you will have to think hard how it works. But as I said, and as you see from your simpler example, things should still be working as expected. The only issue is that it is hard to reason what is expected. :-)

And of course there could be a bug. But I will need a simpler reproduction first to do anything about it.
