### ISSUE TITLE
Subtemplates wrapped in Block Helper Component not able to access current component instance

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-blaze-components#50]
[This example](https://github.com/peerlibrary/meteor-blaze-components#components) doesn't work if you wrap `{{> subTemplate}}` inside a Blaze Component block helper.

Here's a reproduction:
http://meteorpad.com/pad/ZMbC8Ta6ocS45MySk/Blaze%20Component%20Test

I would actually need to pass `currentComponent` into it to access it.

``` handlebars
{{#BlockBlazeComponent}}
    {{> subTemplate currentComponent}}
{{/BlockBlazeComponent}}
```

If the block helper was a regular Blaze block helper, it has no issues accessing the component instance.

**Comment by mitar** [comment]
It works like this: http://meteorpad.com/pad/Z6HuqJsaviAEwxABZ/Copy%20of%20Blaze%20Component%20Test

I would say that this is by (current) design. Blaze templates have two types of parents, one chain of parents which skips over block helpers, and another which goes over all templates.

In Blaze Components we have only one type of parents, so when you do:

``` handlebars
<template name="ExampleComponent">
  <button class="increment">Click me</button>
  {{#Block}}
    {{> subTemplate}}
  {{/Block}}
</template>
```

~~You really do:~~

``` handlebars
<template name="ExampleComponent">
  <button class="increment">Click me</button>
  {{> Block}}
</template>

<template name="Block">
  <div class="block">
    {{> subTemplate}}
  </div>
</template>
```

~~So if you want to access from `subTemplate` helper on `ExampleComponent`, you have to use `componentParent`.~~

~~Now, I think such explicit and only one chain of parent-child relationships is clearer to reason about. But it does mean that when you wrap something into a block helper (or even when you would do something like `{{> NotReallyBlock args 'subTemplate'}}` you add a component in-between. With `{{>` is maybe clearer, but with `{{#Block}}` is the same. For me is just a different way (syntactic sugar) of component inclusion.~~

What do you think? Does this makes things less reusable? Less composable?

> I would actually need to pass currentComponent into it to access it.

You do not really want to do that, because you are making a component a data context.

**Comment by mitar** [comment]
Huh. I am lying. There should not be any difference between:

``` handlebars
<template name="ExampleComponent">
  <button class="increment">Click me</button>
  {{#Block}}
    {{> subTemplate}}
  {{/Block}}
</template>
```

And:

``` handlebars
<template name="ExampleComponent">
  <button class="increment">Click me</button>
  {{#Block}}
    <p>Counter: {{componentParent.counter.get}}</p>
    <p>Message: {{componentParent.customHelper}}</p>  
  {{/Block}}
</template>
```

But there is.

**Comment by mitar** [comment]
Thank you for reporting.

**Comment by rclai** [comment]
Okay, no problem.

**Comment by mitar** [comment]
So in fact block helper component becomes a sibling of the block helper content. A bit surprising, but probably reasonable if we want to have only one chain of component tree.

**Comment by offthegrass** [comment]
if I do

```
{{#ParentComponent}}

  {{#FormComponent}}
    {{> InputComponent}}
  {{/FormComponent}}

{{/ParentComponent}}
```

both `FormComponent` and `InputComponent` have `componentParent` `ParentComponent`.

I would expect
- `FormComponent` to have `componentParent` `ParentComponent`, 
- `InputComponent` to have `componentParent` `FormComponent`.

no?

**Comment by mitar** [comment]
I initially thought that this is how it should be. You do not really want to depend on how many components `FormComponent` is implemented with before it gets to `Template.contentBlock`.

Does this bring issues to you when using it, or it is just esthetics?

**Comment by offthegrass** [comment]
it does cause issues. I'd like to do:

```
  {{#FormComponent}}
    {{> InputComponent}}
    {{> InputComponent}}
    {{> InputComponent}}
    {{> ButtonComponent type="submit"}}
  {{/FormComponent}}
```

``` coffee

class Form extends BlazeComponent
    @register 'Form'

    events: -> [
        'submit': @submit
    ]

    submit: (e) ->
          ...
        for input in @componentChildrenWith 'input'
            @checkInput(input)
```

I'm sure I can do it another way, but this is the most logical imo. 

> You do not really want to depend on how many components FormComponent is implemented with before it gets to Template.contentBlock.

I don't understand what you mean.

**Comment by mitar** [comment]
Imagine that `#FormComponent` would be implemented as:

``` handlebars
<template name="FormComponent'>
  {{#WrapperComponent}}
    {{> Template.contentBlock}}
  {{/WrapperComponent}}
</template>
```

Should `InputComponent` have as a parent `FormComponent` or `WrapperComponent`?

**Comment by bensmeets** [comment]
I was struggling with this whole situation as well earlier. It is because for me it feels that Inheritance and Structure are mixed and matched. E.g., what happens if inputComponent's class extends from WrapperComponent (just to say something nutty, to make the point). The structure of the html feels like defining relations, but so are the inheritances in the class.

But to the point, in the above example, it makes sense for me personally if the parent of Input would be Wrapper.

**Comment by rclai** [comment]
`{{> Template.FormComponent}}` is `{{> Template.contentBlock}}` right?

The way Blaze works, when you do:

``` handlebars
<template name="myTemplate">
{{#blockHelper}}
  {{regularBlazeHelper}}
{{/blockHelper}}
</template>
```

And in the `regularBlazeHelper` helper:

``` js
Template.myTemplate.helpers({
  regularBlazeHelper: function () {
    console.log(Template.instance());
  }
});
```

`Template.instance()` is the `myTemplate` instance, not `blockHelper` instance. They had [a bug](https://github.com/meteor/meteor/blob/devel/History.md#blaze-3) that they fixed a few versions back regarding that functionality.

It would be valuable in Blaze Components to be able to access the instance of the block helper as well as the one outside of it. Ideas?

**Comment by mitar** [comment]
> `{{> Template.FormComponent}}` is `{{> Template.contentBlock}}` right?

Ah, yes. Fixed. :-)

**Comment by mitar** [comment]
So initially that was the idea behind the difference between `component` and `currentComponent`. So:

``` handlebars
<template name="MyComponent">
  {{#BlockComponent}}
    {{currentComponent}}
  {{/BlockComponent}}
</template>
```

So `currentComponent` would give you access to `BlockComponent` instance, while `component` to `MyComponent` instance.

**Comment by mitar** [comment]
So if all three of you agree that it is OK that the parent component of the content inside a block helper is the block helper, then I can look into making it so. For me it is also more intuitive, but it is different than what Blaze does. Blaze makes parent views/templates skip the block templates.

**Comment by rclai** [comment]
Not sure if this is the right path, but what comes to mind right now is a distinction between:

`BlazeComponent.currentComponent()`

vs

`BlazeComponent.component()`

This idea I draw from the already made concept of accessing the data context:

`BlazeComponent.currentData()`

vs

`BlazeComponent.data()`

What do you think?

**Comment by mitar** [comment]
This is exactly what is already there. :-) But, to make it clear:

``` handlebars
{{> MyComponent a=42}}

<template name="MyComponent">
  {{#with a=44}}
    {{#BlockComponent a=50}}
      {{currentData}}
    {{/BlockComponent}}
  {{/with}}
</template>
```

This will make `currentData` return `{a: 44}`, not `{a: 50}`. So why would `currentComponent` (which already exists, BTW) return `BlockComponent` and not `MyComponent`?

**Comment by offthegrass** [comment]
> Imagine that #FormComponent would be implemented as:
> 
> ```
> <template name="FormComponent'>
>   {{#WrapperComponent}}
>     {{> Template.contentBlock}}
>   {{/WrapperComponent}}
> </template>
> ```
> 
> Should InputComponent have as a parent FormComponent or WrapperComponent?

`InputComponent` should have the parent `WrapperComponent`.

doing

```
<template name="FormComponent>
    {{> InputComponent}}
    {{> InputComponent}}
    {{> InputComponent}}
    {{> ButtonComponent type="submit"}}
</template>

{{> FormComponent}}
```

or

```
<template name="FormComponent>
  {{> Template.contentBlock}}
</template>

{{#FormComponent}}
  {{> InputComponent}}
  {{> InputComponent}}
  {{> InputComponent}}
  {{> ButtonComponent type="submit"}}
{{/FormComponent}}
```

should have the same result.

**Comment by mitar** [comment]
And what should be the hierarchy of data contexts?

**Comment by rclai** [comment]
Regarding https://github.com/peerlibrary/meteor-blaze-components/issues/50#issuecomment-103864748.

I think there should be an option parameter to `parentComponent` to allow you to skip or not skip the block helpers (but that might be a problem if you use it in the template and want to chain something (but nest expressions is coming)). Or maybe a totally different function called `currentParentComponent` LOL I don't know.

**Comment by rclai** [comment]
Actually I think `currentParentComponent` (or `currentComponentParent` lol) doesn't sound bad, does it?

**Comment by offthegrass** [comment]
I think it should be the same as if you had rendered it inside the component instance, so

``` coffee
class Form extends BlazeComponent
    @register 'Form'

     placeholder: ->
       'Placeholder set by Form Component'
```

``` coffee
class WrapperComponent extends BlazeComponent
    @register 'WrapperComponent'

     placeholder: ->
       'Placeholder set by Wrapper Component'
```

```
<template name="FormComponent>
    {{> InputComponent placeholder=placeholder}}
</template>

{{> FormComponent}}
```

_Placeholder set by **Form** Component_

```
{{#Form}}
    {{> InputComponent placeholder=placeholder}}
{{/Form}}
```

_Placeholder set by **Form** Component_

```
<template name="FormComponent>
  {{#WrapperComponent}}
      {{> InputComponent placeholder=placeholder}}
  {{/WrapperComponent}}
</template>

{{> FormComponent}}
```

_Placeholder set by **Wrapper** Component_

```
{{#FormComponent}}
  {{#WrapperComponent}}
      {{> InputComponent placeholder=placeholder}}
  {{/WrapperComponent}}
{{/FormComponent}}
```

_Placeholder set by **Wrapper** Component_

```
<template name="FormComponent>
  {{#WrapperComponent}}
      {{> InputComponent placeholder=componentParent.placeholder}}
  {{/WrapperComponent}}
</template>

{{> FormComponent}}
```

_Placeholder set by **Form** Component_

```
{{#FormComponent}}
  {{#WrapperComponent}}
      {{> InputComponent placeholder=componentParent.placeholder}}
  {{/WrapperComponent}}
{{/FormComponent}}
```

_Placeholder set by **Form** Component_

**Comment by mquandalle** [comment]
I also encounter this problem in a simpler form. I created a minimal clonable reproduction [here](https://github.com/mquandalle/meteor-blaze-components-issue-50).

Here are the templates:

``` html
<body>
  {{#NameComponent}}
    Hello {{myName}}. <!-- Here it does not work -->
  {{/NameComponent}}
</body>

<template name="NameComponent">
  {{>Template.contentBlock}}
</template>
```

and here the component logic:

``` coffeescript
class extends BlazeComponent
  @register 'NameComponent'

  myName: ->
    'Houdini'
```

Is there a way (even hacky) as of today to access the `myName` helper at the HTML comment position?

**Comment by mitar** [comment]
Directly from the template? Probably not. You can create a template helper maybe to do that. `{{blockHelperAccess 'myName'}}` which would do `componentParent().componentChildren(name)[0].name` or something.
