### ISSUE TITLE
README base example doesn't work when subTemplate is a component

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-blaze-components#54]
Is this supposed to function like this?

http://meteorpad.com/pad/YkEWg3FP4JvEYSFxT/Blaze%20Component%20Bug?

When the `subTemplate` was not a component, it worked fine, but when I turned it into a component, it stops working.

In order to make the component work, I had to make it inherit the `ExampleComponent` component.

**Comment by mitar** [comment]
Of course, because template helpers are resolved to the closest component. If you use `subTemplate` which is not a component, that is the `ExampleComponent`. If you make `subTemplate` a component, then that is `subTemplate`. You have to then do `{{componentParent.counter.get}}`.

**Comment by rclai** [comment]
Oh... I see.

**Comment by rclai** [comment]
Oh by the way, I was testing it out and noticed that my brain naturally wanted to use `parentComponent`, and realized that it was `componentParent`. I think perhaps it should be renamed to `parentComponent`. I think it's because I was used to doing `Template.parentData()`.

**Comment by mitar** [comment]
Yea. I was bitten by this myself few times already. I named it `componentParent` so that it has the common prefix "component". If you look at [these methods](https://github.com/peerlibrary/meteor-base-component/blob/master/lib.coffee#L173), they so nicely start with "component" prefix. :-)

**Comment by mitar** [comment]
But maybe this is one of those cases when consistency is not the best and an exception would be better.

**Comment by rclai** [comment]
Haha, that's funny xD.

**Comment by rclai** [comment]
What about `extendComponent` and `renderComponent`? xD

**Comment by mitar** [comment]
Open a ticket in this repository, suggesting a rename, and let people vote.

**Comment by offthegrass** [comment]
> What about extendComponent and renderComponent? xD

`componentExtend` and `componentRender` don't work, and neither does `nameComponent` or `childrenComponent`, so there's no way to achieve camel-case-consistency!

dot notation would be nice

`component.render`
`component.children`
`component.parent`
`component.name`

**Comment by mitar** [comment]
Dot notation is not easily extendable with CoffeeScript.

But, as I said. Open a ticket and let's people vote.
