### ISSUE TITLE
Q: Access datacontext in component from #with possible?

### ISSUE THREAD

**Issue by benjamin79** [peerlibrary/meteor-blaze-components#55]
How can i access people in the component? I tried this.data().people. 

```
 {{#with collection='people'}}
             {{> SmartInputComponent  name='firstname'}}
            {{> SmartInputComponent  name='lastname'}}
  {{/with}}  
```

Or isn´t this possible right now? I don´t want to repeat the collection='people' in every time.

Thank you.

**Comment by mitar** [comment]
(Sidenote: If those values are really static strings, then you are probably better of passing them as component arguments.)

In the template you can access parent data contexts with `../collection`, in the code with `Template.parentData()`.
