### ISSUE TITLE
Errors Running The Example & Demo Projects - SOLVED

### ISSUE THREAD

**Issue by castlefields** [peerlibrary/meteor-blaze-components#57]
This a note to everyone else who may experience the same issues as me.

On Cloning the project and running Meteor within the Example & Demo folders I was bombarded with a host of errors in the Chrome Console.

My Terminal reported:-

Meteor 1.1.0.2 is available. Update this project with 'meteor update'

On running Meteor Update both example projects now run.

@mitar Maybe worth updating the Release within the above folders to METEOR@1.1.0.2

**Comment by mitar** [comment]
I cannot reproduce this with demo. I cloned from scratch and it works for me:

```
[[[[[ ~/Temp/meteor-blaze-components/demo ]]]]]

=> Started proxy.                             
=> Meteor 1.1.0.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           

Changes to your project's package version selections:

aldeed:template-extension     removed from your project
peerlibrary:base-component    upgraded from 0.8.0 to 0.10.0
peerlibrary:blaze-components  upgraded from 0.8.0 to 0.12.0

=> Started your app.                          

=> App running at: http://localhost:3000/
```

No errors in web console either.

**Comment by castlefields** [comment]
@mitar Interesting as I thought it maybe a 'Windows Thing', but I also got the same errors on my Mac. Additionally on getting into work this morning I cloned the repo on my work PC and still no joy, but as detailed above, on meteor update, everything worked...

``` javascript
Changes to your project's package version selections from    
updating the release:                                        

autoupdate          upgraded from 1.2.0 to 1.2.1             
blaze               upgraded from 2.1.0 to 2.1.2             
meteor              upgraded from 1.1.5 to 1.1.6             
minifiers           upgraded from 1.1.4 to 1.1.5             
minimongo           upgraded from 1.0.7 to 1.0.8             
observe-sequence    upgraded from 1.0.5 to 1.0.6             
spacebars-compiler  upgraded from 1.0.5 to 1.0.6             
templating          upgraded from 1.1.0 to 1.1.1             
tracker             upgraded from 1.0.6 to 1.0.7             

example: updated to Meteor 1.1.0.2.                          

Changes to your project's package version selections from    
updating package versions:                                   

aldeed:template-extension     removed from your project      
peerlibrary:base-component    upgraded from 0.8.0 to 0.10.0  
peerlibrary:blaze-components  upgraded from 0.8.0 to 0.12.0  
```

**Comment by mitar** [comment]
So if you clone from scratch and you just run `meteor` in the demo app, when you open it in Chrome, you get errors? What are errors exactly?

**Comment by castlefields** [comment]
@mitar Typically I did not note them down and they are not visible now - sorry. 

From memory there where ones like - Template not defined, also an issue with ReactiveVar...

Do you think it was one of the other packages updating that made everything gel together ?

**Comment by mitar** [comment]
I think it might be just bad cache.

**Comment by castlefields** [comment]
@mitar My intention of reporting the issue, was that from reading the specs, I really wanted to use this  package rather than others I had reviewed, I didn't want potential adopters to be put off, as I almost was, when I couldn't even get the demo to work. Shame we can't see the exact cause, but happy its now working !

**Comment by mitar** [comment]
Yes, thank you for reporting it! I really appreciate it. I would just like to know the root of the cause. It seems to me that your upgrade has some side effect which fixed the problem. I would like to know what was the real problem.
