### ISSUE TITLE
Possible to get complete document in event?

### ISSUE THREAD

**Issue by benjamin79** [peerlibrary/meteor-blaze-components#58]
Bevore blaze components (which i like very much btw.) i could get the complete document on click in a array list.

```
   <ul id='{{dropdownId}}'  class="dropdown-content" >
            {{#each users}}
            <li class="multiselect"  value={{value}}><a href="#!">{{user}}</a></li>
            {{/each}}
    </ul>

'click .multiselect': function() {  console.log(this) ...
```

users is an array of the Meteor.users... from mongo. Before i was able to get the complete doc from the clicked element with 'this'. How would i achieve the same thing now.

thank you

**Comment by mitar** [comment]
I think you want to use `this.currentData()` call inside the event handler.
