### ISSUE TITLE
Get vanilla Blaze Template instance from a child Blaze Component?

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-blaze-components#63]
``` handlebars
<template name="vanillaBlaze">
  {{> someBlazeComponent}}
</template>
```

``` js
BlazeComponent.extendComponent({
  someMethod: function () {
    var parentTemplateInstance = ''; // How to get `vanillaBlaze` template instance?
  }
}).register('someBlazeComponent');
```

`this.componentParent` did not work.

**Comment by mitar** [comment]
You should not want that. ;-)

But otherwise I would do `this._componentInternals.templateInstance.parent()` using [aldeed:template-extension](https://github.com/aldeed/meteor-template-extension).

**Comment by rclai** [comment]
I know but I was asking for someone else, but he decided to just pass the data into the component.
