### ISSUE TITLE
Better ES6 examples

### ISSUE THREAD

**Issue by pixelass** [peerlibrary/meteor-blaze-components#64]
I really like the library. I hate the fact tho, that all the examples are in Coffeescript. 
Isn't it time to drop CS and go for ES6 all the way?

I think in some cases it is hard to figure out how some things work in ES6.

**Comment by mitar** [comment]
Feel free to make more examples. :-) You can write a blog post about them, you can write an example project. I would not be adding more content to the README, because it is already long, but I would be glad to link to some external resources if they would be made by the community.

**Comment by pixelass** [comment]
maybe someone could explain how this would look in ES6

``` es6
class RealTimeInputComponent extends AutoSelectInputComponent
  @register 'RealTimeInputComponent'

  events: ->
    super.concat
      'keyup input': @onKeyup

  onKeyup: (event) ->
    $(event.target).change()
```

specifically: 

``` es6
  events: ->
    super.concat
      'keyup input': @onKeyup
```

**Comment by mitar** [comment]
``` javascript
class RealTimeInputComponent extends AutoSelectInputComponent {
  events() {
    return super.events().concat([{
      'keyup input': this.onKeyup
    }]);
  }

  onKeyup(event) {
    $(event.target).change();
  }
}

RealTimeInputComponent.register('RealTimeInputComponent');
```

**Comment by pixelass** [comment]
Thx a bunch.. 

This helps a lot.

BTW I am currently building material-design components with your lib. I will gladly provide some of its code as examples when it's done. I am using ES6 and Jade so I guess it is a nice example of transpiler support of your lib.

Keeping this issue open?

Feel free to close the issue if you think we're done here.

**Comment by mitar** [comment]
Yea, that would be great to have!

I will close the then the ticket.
