### ISSUE TITLE
String interpolation in component arguments

### ISSUE THREAD

**Issue by pixelass** [peerlibrary/meteor-blaze-components#67]
Is it possible to do something like this?

``` handlebars
{{>myComponnent option="foo:{{#if foo}}yes{{/if}}{{#else}}no{{/else}}"}}
```

or 

``` handlebars
{{>myComponnent option="foo:{{foo}}"}}
```

I am writing my components in Jade so there I can at least use this

``` jade
+myComponnent(option="foo:#{foo}")
```

but obviously I don't want them to be tied to any syntax or transpiler logic

I didn't find any documentation so maybe you can help me find an answer to this.

**Comment by mitar** [comment]
No. This is not possible in Blaze. It is also probably too much logic for Handlebars pure separation of concerns.

You can do:

``` handlebars
{{>myComponnent option=option}}
```

``` coffeescript
class myComponent extends BlazeComponent
  option: ->
    "foo:#{if @data().foo then 'yes' else 'no'}"
```

**Comment by pixelass** [comment]
Yea I was guessing that.. I was just wondering why I could do some string interpolation in Jade but not in spacebars since the Jade implementation of meteor only uses Jades lexer and syntax..

I will just have the people build this logic into their templates. 

Thx for the answer.

Issue can be closed.
