### ISSUE TITLE
Q: Is this package alive and maintained?

### ISSUE THREAD

**Issue by serkandurusoy** [peerlibrary/meteor-blaze-components#68]
First things first, kudos on such a forward thinking package with such a clean API.

I'm currently overhauling a large meteor project with lots of template code repetition and porting to react is out of question.

So within the confines of blaze, I think this package could help me a lot.

But, it seems to me that the project has been frozen about 2 months ago with no commit activity, neither any discussion/commenting on the issues.

So I'm wondering if you are planning to support/maintain this package and perhaps even publish new releases?

Thanks.

**Comment by mitar** [comment]
It just means that it is a stable project without bugs. :-) Used in production a lot. :-)

**Comment by serkandurusoy** [comment]
Thanks, this is great to know! :clap:
