### ISSUE TITLE
Access currentData() from constructor when 'args' is specified.

### ISSUE THREAD

**Issue by pward123** [peerlibrary/meteor-blaze-components#69]
Given this in the calling template

```
{{#with itemIds=getItemIds}}
    {{> ItemList args onCheckClicked=getOnItemCheckClicked}}
{{/with}}
```

and this in the ItemList constructor

```
function ItemListConstructor(args) {
    assert(this.currentData().itemIds, 'Expecting itemIds to be defined');
    ...
}
```

the assert is throwing an exception.  If I remove the 'args' in the calling template, the assert no longer throws and I am able to get the itemIds value in the constructor.  Before I create a simple example, I wanted to know if this is expected behavior.

In both cases, I'm able to use the itemIds in the ItemView helpers.  The problem I'm having is just with the constructor.

**Comment by mitar** [comment]
Current data is not available in the constructor. It is only available after the component is created by Blaze, so in `onCreated` and `onRendered`. So in the constructor the object is just simple JavaScript object. There is a ticket #62 which is asking to change this behavior. That `data` or `currentData` should be simply waiting until the content is rendered. But in your case you are not using it in a reactive context, so `currentData` would still return `null` for you in the constructor.
