### ISSUE TITLE
Provide a global template helper to render components dynamically

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#7]
Similar to [Template.dynamic](http://docs.meteor.com/#/full/template_dynamic), but for components.

**Comment by Sivli-Embir** [comment]
:+1: Trying to create a form with dynamic inputs components. What is the reason `Template.dynamic` does not work? I can't even get normal templates to render inside a component.

**Comment by mitar** [comment]
Normal components should work inside a component. So if you want to include a normal component that should work well. But it is true that I do not have a test case for that. Feel free to make one. :-)

The other way, it does not work because components are not templates. They just use templates for content. So when you do `Template.dynamic` you are in fact including just the raw template content, not the component.

**Comment by Sivli-Embir** [comment]
Odd, it was not working for me. May be a bug related to #30 I will review.

**Comment by offthegrass** [comment]
@Kestanous please post your findings. Did you get anywhere with using FlowLayout as a component? (https://github.com/peerlibrary/meteor-blaze-components/issues/19)

**Comment by Sivli-Embir** [comment]
@offthegrass I am actually fighting off a head cold so I am only responding to issue today. I will try to investigate more on all points tomorrow, assuming I can thing again.

**Comment by mitar** [comment]
Now you can simply use `Template.dynamic` and pass component's name as a `template` argument. And it will use the component.

But a disclaimer. Often it is better that instead of using `Template.dynamic` to create a method on the current component which is returning such a dynamic value. So that you move this logic into the component. Then somebody else can later on extend/override it in subclasses.

So instead of doing:

``` handlebars
{{> Template.dynamic template=foo}}
```

You could do:

``` coffee
class FooComponent extends BlazeComponent
  renderFoo: ->
    BlazeComponent.getComponent(@data().foo).renderComponent @currentComponent()
```

``` handlebars
{{> renderFoo}}
```

**Comment by rclai** [comment]
Wait a minute, I tried passing the `register`'d name of the component to Template.dynamic. It rendered, but it has no access to the component's methods at all.

**Comment by mitar** [comment]
I have this in [tests](https://github.com/peerlibrary/meteor-blaze-components/blob/master/tests/tests.html#L250). And tests work. So I am not sure what is happening here? Can you get a reproduction going on? Or adding/modifying tests so that they fail in the same way you are observing?

**Comment by rclai** [comment]
Sorry about that, Meteor's shell was [messing with me](https://github.com/peerlibrary/meteor-blaze-components/issues/43#issuecomment-98036484).

**Comment by pward123** [comment]
How do I pass args to the renderComponent call? i.e.

``` Handlebars
{{> renderFoo args blah=1}}
```

**Comment by mitar** [comment]
You cannot, this is a limitation I do not know how to go around: #12.

**Comment by rclai** [comment]
@mitar, when you do this:

``` coffee
class FooComponent extends BlazeComponent
  renderFoo: ->
    BlazeComponent.getComponent(@data().foo).renderComponent @currentComponent()
```

Does that render the component while inheriting the instance properties of the `@currentComponent()`?

**Comment by mitar** [comment]
No, it sets current component as parent component. So you can access it and its properties through `@componentParent()`. You can also do that in the handlebars `{{componentParent.bla}}`.

**Comment by rclai** [comment]
Gotcha thanks.
