### ISSUE TITLE
ExposeTemplateHelpersMixin: how to override events

### ISSUE THREAD

**Issue by bartonhammond** [peerlibrary/meteor-blaze-components#74]
I'd now like to include the base events so I can intercept them and process according to the Webix library.  For example, the [atNavButton.js](https://github.com/bartonhammond/webix-components/blob/master/packages/app-core/lib/client/atNavButton.js) has the following initialization:

```
// Simply 'inherites' events from AccountsTemplates
Template.atNavButton.events(AccountsTemplates.atNavButtonEvents);
```

for now, my temporary [AccountsTemplates.atNavButtonEvents](https://github.com/bartonhammond/webix-components/blob/master/packages/app-lib/lib/helpers/at_nav_button.js) implementation just logs to the console:

```
AT.prototype.atNavButtonEvents = {
    'click #at-nav-button': function(event){
      event.preventDefault();
      console.log('AT.prototype.atNavButtonEvents.click');
    },
};
```

In my [ExposeTemplateHelpersMixin](https://github.com/bartonhammond/webix-components/blob/master/packages/app-core/lib/client/ExposeTemplateHelpersMixin.js) 
-   where should I stash the "template.__eventMaps" in the mixinParent
-   how to listen for these events in my BlazeComponent?

```
ExposeTemplateHelpersMixin = BlazeComponent.extendComponent({
  mixinParent: function (mixinParent){
    if (mixinParent) {
      var template = mixinParent.template();

      if (_.isString(template)) {
        template = Template[template];

        ///
        /// what to do w/ template.__events?????????
       /// 
        var name;

        for (name in template.__helpers) {
          name = name.substr(1);
          mixinParent[name] = Blaze._getTemplateHelper(template, name, Template.instance);
        }      
      }///if
    }
    return ExposeTemplateHelpersMixin.__super__.mixinParent.apply(this, arguments);
  }//mixinParent
});
```

Thanks, again, for your help.  I hope this will be enough for me to make a lot of progress w/ Webix.

**Comment by bartonhammond** [comment]
So I made some progress but it's not very elegant.  

If you click the Webix button http://webix-components.meteor.com/ w/ the Developer Tool open you'll see the log from the useraccounts:base event for "click #at-nav-button';

Currently I'm handling the 'click #at-nav-button' event within the Webix button on click handler and then calling the base templates event.  I'd rather handle the event w/in the BlazeComponent in the events function. But not a sure how to tie or associate the Webix button back to the BlazeComponent.events function, see [atNavButton](https://github.com/bartonhammond/webix-components/blob/master/packages/app-core/lib/client/atNavButton.js)

```
  onRendered: function() {
    webix.ui({
      view:"button", label:this.text() , id:"_at-nav-button", width: 100
      , click:function(_event) {
       /////////////////////////////////////////////    faking the eventContext for the base class....
        var eventContext = {};
        eventContext.currentTarget = $('#mybody')[0];
        eventContext.templateInstance = function() {};
        Template.atNavButton.__eventMaps[0]["click #at-nav-button"].call(eventContext, event);
      }      
    }, $$('at-nav-button'));
  },
```

**Comment by bartonhammond** [comment]
Turns out the [meteor-template-extension](https://github.com/aldeed/meteor-template-extension) is what I was looking for.  

Thanks for all your help!

**Comment by mitar** [comment]
I am reopening because I want to think a bit more about this.

**Comment by mitar** [comment]
The `master` now contains Blaze Components version which extend existing templates.
