### ISSUE TITLE
Access method on a component

### ISSUE THREAD

**Issue by Narven** [peerlibrary/meteor-blaze-components#77]
Hi,

this is not a bug, but I need some explanation if blaze components can help me do this.

If i have a component called `foo` and another component/blaze template called `bar`, how can i trigger from `bar` something to happen on `foo`. basicly i want to call a method on `foo` from `bar`

on bar.js

`foo.explode()`

thanks

> PS: if this is no possible with blaze components, can you point me into a direction where this is possible? foo needs to be abstracted enought, with a bunch of methods that i can call from outside.

**Comment by mitar** [comment]
You just get a reference to that component instance somehow and call it. You can use `componentParent` or `componentChildren` to traverse the component tree. Or you use some other way to pass that reference around.

**Comment by Narven** [comment]
That _...instance somehow and call it._ is really helpfull.

Sometimes I really think that you guys only build these things for your self's, and not for anybody else (specially does that do not understand so much of it).

You asking me to put it on a public place so everybody could see it was for you to give such an awesome response like that? I'm pretty sure that all the future generations will be delighted and fulfill with the knowledge pass on to them.

Thanks

**Comment by mitar** [comment]
Yes, we build it for ourselves and then we give it to others for free if anyone else finds it useful. Everything else is extra. Or, have I missed something and you hired me to build something for you?

I think I pointed you also to methods which you can use to get those instances. Have you checked them out?

**Comment by Narven** [comment]
I have:

```
var Foo = BlazeComponent.extendComponent({

  explode: function () {
      return 'explode';
  },
...
```

I'm trying to do this (inside Bar.js):
`BlazeComponent.getComponent('Foo').explode()`

What i'm missing to make it work?

**Comment by mitar** [comment]
`BlazeComponent.getComponent('Foo')` returns a component class, not component instance. Component instance is something which is available when component is rendered into the template.

Of course you can create also class-level methods, then you can call them on the class:

```
var Foo = BlazeComponent.extendComponent({});
Foo.explode = function () {
  ...
}
```

But this is something else.

You might consider reading a bit on topic of JavaScript classes and objects.

**Comment by mitar** [comment]
[This forum post](https://forums.meteor.com/t/proposal-for-blaze-2/1246/50?u=mitar) explains a bit more.
