### ISSUE TITLE
Create FlowRouter Layout manager for Blaze Components

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#79]
See example:

https://gist.github.com/offthegrass/3c1491cc9d5b4c5cb5d0

It would be great if this would be made into a package and documented here in the README how to use it.

**Comment by mitar** [comment]
cc @offthegrass care to make it?

**Comment by DominikGuzei** [comment]
Hey @mitar, we are also interested in making this possible – so maybe i will take shot at it within the next few days! Btw. blaze-components will become the first-class render layer for the next major version of [space:ui](https://github.com/meteor-space/ui) and we will rename it to `space:flux` + are planning to add React / Angular support in the future.

**Comment by rhyslbw** [comment]
+1

**Comment by mitar** [comment]
@DominikGuzei great stuff to learn. BTW, the whole idea of Blaze Components is that they are build around [base component](https://github.com/peerlibrary/meteor-base-component). The idea is that there would then be also React Components, and Web Components. But I do not have time nor too much interest to make those others myself. But maybe you could consider doing in this way. So the hierarchy could be then:

base component -> blaze component -> space:flux component
base component -> react component -> space:flux component
base component -> angular component -> space:flux component

What do you think?

The main purpose of base component is that we would have a common tree of components to navigate (imagine great inspection tools which could work across all these rendering systems), no matter the rendering system. See my [comment here](https://github.com/peerlibrary/meteor-blaze-components/issues/80#issuecomment-146030540) why having a good navigation in the tree of components is important to have refactorable code.

**Comment by DominikGuzei** [comment]
Hey @mitar, that sounds great indeed!
I will have to read through the base component source and think about ways this could work.
But i think you are right that it would be great to have a unified API for the various rendering engines.
I just started using the components API like `@currentData()` related to getting data in various scenarios and i love it! Still a lot to learn here :wink:

Will keep you updated as we move along and btw. if you like to follow along with our discussions, we have a gitter chat for the meteor-space framework now: https://gitter.im/meteor-space/general

**Comment by rhyslbw** [comment]
Hey @mitar, we'll definitely consider this as it addresses the impedance mismatch with the different view syntax when introducing space:flux. This sounds like a nice way to use React or Angular in Meteor, so it should get some decent attention

**Comment by mitar** [comment]
Do you have any ticket where we could continue this discussion (we hijacked a bit this ticket)?

> This sounds like a nice way to use React or Angular in Meteor, so it should get some decent attention

So base component just provides tree structure, the naming of components, and API to create them and render them. I think everything except for the last part is clear. And for rendering I have not yet decided how exactly to do it. So I would like to have a render call where a parent component could say to child component render, but that would work no matter which type of a child component it is. The question is if we should pass data context or not to it, for example.

**Comment by DominikGuzei** [comment]
Hey @mitar, how about issue #14? This seems like the same discussion :wink:

**Comment by mitar** [comment]
Yea, let's move there. :-)

**Comment by mitar** [comment]
What is progress on the layout manager? Because otherwise I will look into this. But I would not like to duplicate work.

**Comment by DominikGuzei** [comment]
Hey @mitar, yeah if you have time please look into it - i am buried with work, so i would really appreciate that! :wink:

**Comment by mitar** [comment]
I made this pull request: https://github.com/kadirahq/blaze-layout/pull/50

**Comment by mitar** [comment]
I use this to register a root component (so that all other components are inside the same tree):

``` handlebars
<template name="RootComponent">
  <div id="__blaze-root"></div>
</template>

<body>
  {{> RootComponent}}
</body>
```

``` coffee
class RootComponent extends BlazeComponent
  @register 'RootComponent'

BlazeLayout.setRoot '#__blaze-root'
```

**Comment by mitar** [comment]
Then you can normally use `BlazeLayout`:

``` javascript
BlazeLayout.render('LayoutComponent', {top: 'HeaderComponent', main: 'MainComponent'});
```

``` handlebars
<template name="LayoutComponent">
  {{> Template.dynamic template=top}}
  {{> Template.dynamic template=main}}
</template>
```

``` coffee
class LayoutComponent extends BlazeComponent
  @register 'LayoutComponent'
```

**Comment by DominikGuzei** [comment]
Hey @mitar, awesome - thanks for implementing this! I will give it a try tomorrow and report back!

**Comment by mitar** [comment]
Pull request was merged upstream into `blaze-layout` package.

**Comment by mitar** [comment]
A new version (2.2.0) of the `blaze-layout` package has just been published.

**Comment by mitar** [comment]
I am leaving this ticket open for the following todo:
- document in the README how to use the package with flow router
- maybe create a simple package which creates a root component and calls `BlazeLayout.setRoot`, so practically:

``` handlebars
<template name="RootComponent">
  <div id="__blaze-root"></div>
</template>

<body>
  {{> RootComponent}}
</body>
```

``` coffee
class RootComponent extends BlazeComponent
  @register 'RootComponent'

BlazeLayout.setRoot '#__blaze-root'
```

**Comment by JesperWe** [comment]
Hi guys, I am trying to integrate FlowRouter and BlazeComponent for a new project, and I found these issues/PRs, but after reading them there is too much coffescript that I have trouble following, sorry... Any chance you could show how to instanciate a BlazeComponent with a data context from FlowRouter 2.2+/BlazeLayout using ES2105?

**Comment by mitar** [comment]
It should just work as you would do with Blaze templates.

**Comment by DominikGuzei** [comment]
Haha, im loving it … @JesperWe please take 5 minutes to at least skim over http://coffeescript.org/ to get the basic idea about Coffeescript. It would never strike me to ask you for a ES5 example, just because i am too lazy to skim over ES2015 syntax. Coffeescript == just Javascript with (awesome) syntactic sugar, not a different language. Sorry if that sounds rude … take it with a grain of frustration on my side.

**Comment by mitar** [comment]
This was implemented as this package: https://github.com/peerlibrary/blaze-layout-component
