### ISSUE TITLE
Require instead of add

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-blaze-components#9]
I think `requireMixin` better describes what the function does than `addMixin`. `Add` doesn't describe that the function will not do anything in case the mixin is already present. With `Require` it's more intuitive to imagine that multiple mixins can call it. And it works just like `require` calls from other platforms (node etc).

**Comment by mitar** [comment]
I am trying to keep `require` if we will need some API to add a dependency before the current mixin. And `add` adds after it.
