### ISSUE TITLE
Passing arguments using args broken?

### ISSUE THREAD

**Issue by JesperWe** [peerlibrary/meteor-blaze-components#93]
The docs say "sometimes you want to pass arguments to component's constructor. You can do that as well with the special args syntax"

So I try:

```
class Foo extends BlazeComponent {
    onCreated( bar ) {
        super.onCreated();
        console.log( "onCreated(" + bar + ")" );
        this.bar = bar || 'undefined';
    }
}

Foo.register( 'Foo');
```

```
<template name="FooTest">
    Foo {{> Foo args 'Test'}}
</template>

<template name="Foo">
    Result: {{ bar }}
</template>
```

But onCreated() gets called with no arguments, so this.bar does not get the argument value.

**Comment by mitar** [comment]
Arguments are passed to the component's constructor, not `onCreated`.

**Comment by mitar** [comment]
Although, there is really no reason why they could not be passed to the `onCreated` as well. But they are not currently.

**Comment by rclai** [comment]
``` js
class Foo extends BlazeComponent {
    // This is the constructor
    constructor(bar) {
       console.log( "onCreated(" + bar + ")" );
       this.bar = bar || 'undefined';
    }
}

Foo.register( 'Foo');
```
