### ISSUE TITLE
renaming is irritating (childrenComponents)

### ISSUE THREAD

**Issue by pixelass** [peerlibrary/meteor-blaze-components#94]
`childrenComponents` is very irritating.

Maybe you should have called it `childComponents` which would be grammatically correct

**Comment by mitar** [comment]
Whoops. :-)

**Comment by mitar** [comment]
And it is even shorter.

**Comment by mitar** [comment]
What others think?

**Comment by mitar** [comment]
My English speaking friend is saying that while `childComponents` is grammatically correct, it is incorrect for the API we have, which is that we are returning all children (which are components) of a component, and not components of one child.

**Comment by pixelass** [comment]
that is why I think `componentChildren` was correct ;) for me it was very straight forward. Maybe I should have paid more attention to the issue discussing the change.. my bad.

I'm totally fine with the "incorrect" naming. I just think it is a little confusing right now.

It is all not really pretty. also please note it is only a suggestion.

**Comment by mitar** [comment]
OK, is is true that we had pretty good consensus on renaming `componentParent` to `parentComponent` (because it was non-intuitive), and I did renaming of componentChildren`to`childrenComponents` to match it.

**Comment by Sivli-Embir** [comment]
I feel your friend is correct from the view point of written English but that is not the the standard I often see in the programing world. `childrenComponents` is a double plural that means "many children each with many components". But really we have "many children who are a component" or "we have many [childComponent]s". Since the thing is a childComponent and the api returns multiple I also feel `childComponents` is ideal.

**Comment by pixelass** [comment]
I agree on the `parentComponent` because now we know the parent is a component and not a DOMElement

I guess the same goes for the `children`

`componentChildren` would suggest that also DOMElements could be returned. So either way your change makes sense.

I agree with @Kestanous it is not only a grammar issue but also suggests that there are children with components?

I hope others will put in their five cents. I'm not sure if my suggestion is correct so the opinion of others is appreciated.

**Comment by mitar** [comment]
I am leaning towards `childComponents` slowly. Especially because it is shorter.

Any objections to change the API once more? :-)

**Comment by pixelass** [comment]
the last migration took me about 2 or 3 minutes ;) 

I'd say, go for it.

**Comment by rclai** [comment]
I think `childComponents` is pretty accurate on @Kestanous' end from a grammatical and programmatic perspective.

**Comment by mitar** [comment]
Renamed. Thanks for the feedback.
