### ISSUE TITLE
about to release a material-design  library

### ISSUE THREAD

**Issue by pixelass** [peerlibrary/meteor-blaze-components#95]
I am about to release a library completely written in ES2015 using your components. (I mentioned this before)
You can see a production usage here [https://codefights.com](https://codefights.com)

I created two libraries, one of which will be open-sourced either today or within this week.

Does this help you in any way?

**Comment by mitar** [comment]
That sounds great. I am just currently using materialize + Blaze Components myself. It works pretty well, but my issue is that it is unclear how to change color scheme of material-design based components. Not sure how you solved that in your case.

> Does this help you in any way?

In which sense? It will probably help me in my projects. ;-)

**Comment by mitar** [comment]
BTW, I am also working on the [voting app](https://github.com/mitar/council-app).

**Comment by pixelass** [comment]
the first release will be an alpha. I wrote it for our relaunch so it is just a first implementation.

Right now there are no "real styling options" while I am trying to make it very similar to polymer, so the next version will introduce a lot of changes.

As soon as this is released I will do a complete rewrite, now that I know a lot more about your library and meteor.

You mentioned it would be nice to have here: https://github.com/peerlibrary/meteor-blaze-components/issues/64

That's why I am asking if it would help in any way.

**In my case the components look something like below:**  
(renders a paper-button with ripples and all the polymer options)

``` handlebars
<template name="someThing"
{{#PaperButton className="funky-color" 
               eventHook="awesome"}} 
   click me please
{{/PaperButton}}
{{#PaperButton className="funky-color"
               noink="true"
               raised="true"
               toggles="true"
               eventHook="superAwesome"}} 
   click me please
{{/PaperButton}}
</template>
```

``` css
paper-button.funky-color {
  background: pink;
}
```

``` javascript
Template.someThing.events({
  'click [event-hook=awesome]': function(event, instance) {
    console.log('hey you clicked me... awesome');
  },
 'click [event-hook=superAwesome]': function(event, instance) {
    console.log('hey you clicked me... super awesome');
  }
});
```

<img width="841" alt="paperbutton" src="https://cloud.githubusercontent.com/assets/1148334/10618540/64dcadce-7725-11e5-82dd-1d74a8d15039.png">

**Comment by mitar** [comment]
Yea, examples are great. :-) Cool, I am looking forward to see your stuff.

**Comment by pixelass** [comment]
The release should be up in a few hours. 

The demo page is already deployed and shows "some" examples. Not all components are listed though

http://blaze-material-ui.meteor.com/

**Comment by mitar** [comment]
Looks amazing!

**Comment by pixelass** [comment]
now available... feedback welcome: https://github.com/Code-Fights/blaze-material-ui

**Comment by mitar** [comment]
Great, it is seen in http://components-explorer.meteor.com/ as well. I will have to remove old versions though there.
