### ISSUE TITLE
equivalent of Template.dynamic ?

### ISSUE THREAD

**Issue by hexsprite** [peerlibrary/meteor-blaze-components#97]
I know it's possible using BlazeComponent.getComponent().renderComponent() in my functions but is there something I can use in my templates?

**Comment by hexsprite** [comment]
I see there is https://github.com/peerlibrary/meteor-blaze-components#programmatic-rendering

It is pretty close but it still might be convenient to have a helper for the most common case.

**Comment by mitar** [comment]
In templates you can just use `Template.dynamic`.
