### ISSUE TITLE
Binding event handlers inside the template

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#99]
I think that slowly I am becoming in favor of binding event handlers inside the template instead of the `events` method. So something like:

``` handlebars
<template name="ButtonComponent">
  <button class="red" onClick={{onClick}}>Click me</button>
</template>
```

Or some other similar syntax? Suggestions? Maybe we could have a shortcut for predefined event handlers for all events, so that you can do `<button class="red" onClick>Click me</button>`.

This would call `onClick` method of the component.

Because my current pattern is getting really ugly:
- adding a class to the button
- and then making a selector for that class in the code

``` handlebars
<template name="ButtonComponent">
  <button class="red click-button">Click me</button>
</template>
```

``` coffeescript
events: ->
  super.concat
    '.click-button': @onClick
```

A lot of ugly code just to connect the event. I think it is good to have selectors approach for events, but for most events is always this 1:1 to the element. So I would like to support both.

The question is: how to do it. I would like something which does not require me to parse the DOM after it has been rendered. That `onClick={{onClick}}` is something which gets detected and stored away in the compilation phase.

cc @stubailo

**Comment by stubailo** [comment]
Easiest way would be to create a helper that adds a data attribute and catch all of those events, then delegate then to the right handler yourself.

**Comment by mitar** [comment]
Yes, but data attribute is then rendered to the DOM?

**Comment by mitar** [comment]
See the [README](https://github.com/peerlibrary/meteor-blaze-components#handling-events) and [tutorial](http://components.meteor.com/) for examples and final syntax.

**Comment by mitar** [comment]
The main idea is to use `Blaze._makeAttributeHandler` to register a new Blaze handler for setting attributes to DOM elements. But instead of setting a real attribute, we simply register event handler. In this way we have event handler directly on the DOM element and no event delegation or anything is necessary. A pretty straightforward change. The only tricky thing is to get the event handler all the way to the attribute value because Blaze likes to call all functions it encounters much earlier. :-)
